mongodb/snooty-parser

CHANGELOG.md, snooty/parser.py, snooty/test_parser.py
[Jira ticket](https://jira.mongodb.org/browse/DOCSP-6190)
=> DOCSP-6190: Add validation of 'doc' role links

snooty/main.py
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6849)] Replace `type` field with `filename`
=> DOCSP-6849: Save filename to documents in snooty.assets

snooty/parser.py, snooty/test_project.py
If there is an error loading the `snooty.toml` file, raise diagnostics, followed by throwing `ProjectConfigError`.
This still results in process termination with an unhandled exception, but it's the *right* exception, and the errors are actually printed.
Also eliminate the `_Project.root` instance member because it was misleading (actually the source directory), and unnecessary.
=> bugfix: Properly report snooty.toml errors

snooty/semanticparser.py
I started refactoring `find_toctree_nodes()` based on [this comment](https://github.com/mongodb/snooty-parser/pull/72#discussion_r356050444), but then realized there was a lot of room for improvement 😅
=> Refactor semantic parse layer

snooty/parser.py
For example:
Coverage.py warning: Data file '.coverage.Andrews-MacBook-Pro.local.62747.869453'
doesn't seem to be a coverage data file: Couldn't use data file
'.coverage.Andrews-MacBook-Pro.local.62747.869453': no such table:
coverage_schema
=> Prevent Coverage.py data warnings with Pool.close(); Pool.join()

snooty/rstspec.toml
https://support.google.com/webmasters/answer/79812
=> Add robots option to meta directive

snooty/intersphinx.py, snooty/parser.py, snooty/semanticparser.py, snooty/test_semantic_parser.py, snooty/types.py, test_data/test_semantic_parser/snooty.toml, test_data/test_semantic_parser/source/page4.txt, test_data/test_semantic_parser/source/refrole.txt
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5776)]
- Add diagnostics to semantic parse layer
- Validate `ref_role` nodes in AST
- If valid, append URL to node
- If invalid, throw error
~~Would appreciate any suggestions re: testing!~~
=> DOCSP-5776: Validate references to targets

snooty/rstspec.toml
JIRA: https://jira.mongodb.org/browse/DOCSP-8787
=> DOCSP-8787: adds realm tab sets directives

snooty/parser.py, snooty/test_parser.py
Followup to 072f7c89ec0c302293d9424c3ab73859be9d83a3
=> DOP-891: Skip incomplete target nodes

snooty/main.py, snooty/test_postprocess.py, snooty/test_project.py
[[JIRA](https://jira.mongodb.org/browse/DOP-948)] See #86 for implementation of commit-based builds, upon which this PR builds.
- Support new `--patch` flag
=> DOP-948: Patch-based builds

snooty/rstspec.toml
The csharp links are broken and included and invalid path.
=> fix csharp links

snooty/diagnostics.py, snooty/main.py, snooty/test_diagnostic.py, snooty/test_main.py
https://jira.mongodb.org/browse/DOP-969
=> Dop-969: Add an environment variable to support emitting diagnostics in JSON

snooty/diagnostics.py, snooty/language_server.py, snooty/main.py, snooty/test_diagnostic.py, snooty/test_main.py, stubs/docutils/frontend/__init__.pyi
* Return status code 2 if there are build errors
* Status code 1 now indicates a crash
* Fixed up and refactored our diagnostic levels
=> DOP-922: Report diagnostics with a separate return code

CHANGELOG.md, snooty/n.py, snooty/parser.py, snooty/test_parser.py
[[JIRA](https://jira.mongodb.org/browse/DOP-1210)]
=> DOP-1210: Support ol start attribute

snooty/rstspec.toml
JIRA:
https://jira.mongodb.com/browse/DOCSP-11615
=> DOCSP-11615: update urls for newest versions of Java driver

snooty/main.py
Fixes regression introduced by fff7a161f1b744ec3d240fbafd9b6fbba1e65d8c
=> Save assets to the correct collection

snooty/rstspec.toml
[DOP-1491] Decided to just brute-force these roles until we can come up with a more comprehensive means of supporting role options. Thanks!
=> DOP-1491: Add highlight roles

snooty/rstspec.toml
[DOP-1396] Add `:kbd:` role to highlight keystrokes.
=> DOP-1396: Add kbd role

snooty/gizaparser/nodes.py, snooty/gizaparser/test_extracts.py, snooty/gizaparser/test_steps.py, test_data/steps-test-child.yaml, test_data/steps-test-grandchild.yaml
This also fixes multi-level inheritance, and adds explicit cycle-detection.
=> DOP-1595: Correctly inherit YAML ref names

snooty/main.py, snooty/n.py
Adds a created_at field to snooty documents!
Evidence:
=> DOP-1318: add created_at field to snooty documents

snooty/rstspec.toml
https://jira.mongodb.org/browse/DOCSP-13010
=> (DOCSP-13010): Add dotnet-sdk, xamarin, and git-scm extlink roles

pyproject.toml
@i80and Can you please take a look? We want to use this but cannot until a version is released with looser dependency constraints.
=> Relax dependency constraints

pyproject.toml
Refs: https://github.com/vscode-restructuredtext/snooty-parser/pull/15#issuecomment-813737514
=> Relax docutils version constraint

snooty/rstspec.toml
Hi @schmalliso , as we discussed here's a PR to create the `v4.4` role for the manual.
Let me know if I need to fix anything. Thank you!
=> Add v4.4 manual role

snooty/rstspec.toml
Adding a Java 4.3 API documentation directive
=> Adding Java 4.3 API directive

pyproject.toml
Broaden `pymongo` dependency to all compatible releases.
=> Broaden pymongo dependency

snooty/gizaparser/release.py, snooty/gizaparser/steps.py, snooty/n.py, snooty/parser.py, snooty/rstspec.toml, snooty/test_parser.py
Front-end support will be handled in separate PR, obviously :)
=> DOP-2562: support lineno-start option

snooty/diagnostics.py, snooty/eventparser.py, snooty/gizaparser/nodes.py, snooty/language_server.py, snooty/main.py, snooty/parser.py, snooty/performance_report.py, snooty/postprocess.py, snooty/target_database.py, snooty/test_language_server.py, snooty/test_parser.py, snooty/test_project.py, snooty/test_util.py, snooty/util.py, snooty/util_test.py
This is a big PR, but is broken down into pretty incremental commits that probably make sense to be reviewed in sequence instead of the whole thing at once
Current build artifacts: https://github.com/mongodb/snooty-parser/suites/4441832356/artifacts/117748017
=> DOP-2546: Activate postprocessor in language_server

snooty/intersphinx.py, snooty/main.py, snooty/parser.py, snooty/test_intersphinx.py, snooty/util.py
* Add a --no-cache command line option that can be used to disable caching entirely
* Don't actually send an HTTP request if the file was last updated in the past hour, as the comment states
=> Improve util.HTTPCache

snooty/rstspec.toml
[JIRA](https://jira.mongodb.org/browse/DOCSP-22979)
=> (DOCSP-22979): Create a role to link to new Atlas App Services docs

snooty/main.py, snooty/parser.py
Includes branch name in the manifest file as part of DOP-2986.
=> DOP-2986: Include branch name in manifest file

snooty/rstspec.toml
https://jira.mongodb.org/browse/DOCSP-25782
=> (DOCSP-25782) Adds MongoDB Analyzer custom role to rstspec.toml

snooty/rstspec.toml, snooty/test_parser.py
[Build](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=6345514b7aabe79449f28b50)
=> (DOCSP-25798) Removes saas from Charts custom role path

snooty/rstspec.toml
Hey folks - just wanted to add the C++ SDK info so we can use it in the Realm docs. Thanks!
=> Add the C++ SDK to Realm tabs/role

snooty/rstspec.toml
=> add maui constant

snooty/rstspec.toml
- Update the App Services docs URL to avoid a redirect
=> realm -> atlas/app-services

snooty/rstspec.toml
- Ticket: [DOP-3696](https://jira.mongodb.org/browse/DOP-3696)
=> DOP-3696 Add RST objects for DataLake config

snooty/parser.py, snooty/test_parser.py, snooty/tinydocutils/statemachine.py
Found an additional faulty assertion I added in tinydocutils, and dealt with that as well!
=> DOP-3753: Handle RemovedLiteralBlockSyntax error with no children

snooty/parser.py, snooty/postprocess.py
This ensures that our PageDatabase remains valid for caching purposes.
=> DOP-3878: Move propogate_facets to the postprocessor

snooty/rstspec.toml
I added the Atlas CLI to the language dropdown.
JIRA: https://jira.mongodb.org/browse/DOCSP-33288
=> (DOCSP-33288): Added the Atlas CLI to the language dropdown.

.github/pull_request_template.md
Adds PR template with checks for README
=> DOP-4289: Add PR template

snooty/rstspec-consolidated.toml, snooty/rstspec.toml
DOP-4390
Driver languages were added recently. However, the values were changed as can be referenced in the above ticket's comments.
This is for the `latest` branch.
=> DOP-4390: add drivers languages to rstspec and rstspec-consolidated

snooty/rstspec.toml
see https://github.com/10gen/cloud-docs/pull/5036 for context
=> updated university role to point to paths other than /courses

snooty/rstspec.toml
[DOCSP-38181](https://jira.mongodb.org/browse/DOCSP-38181)
Adds role for Atlas Search Playground URL
=> DOCSP-38181 Set up role for Search Playground URL

poetry.lock, pyproject.toml, snooty/builders/man.py, snooty/flutter.py, snooty/page_database.py, snooty/parser.py, snooty/postprocess.py, snooty/rstparser.py, snooty/tinydocutils/__init__.py, snooty/tinydocutils/directives.py, snooty/tinydocutils/nodes.py, snooty/tinydocutils/statemachine.py, snooty/tinydocutils/states.py, snooty/types.py, snooty/util.py
Replaces https://github.com/mongodb/snooty-parser/pull/575
=> Bump dependencies

snooty/rstspec.toml
[DOCSP-37734](https://jira.mongodb.org/browse/DOCSP-37734)
Adds links for feedback engine pages for Atlas Search and Atlas Vector Search
=> DOCSP-37734 add links to user voice pages

HACKING.md
Removed the prereq for gpg as we sign with SSH keys instead !
=> update readme for release process

snooty/rstspec.toml
=> DOP-4511: add link type for community-built badges

snooty/rstspec.toml
For a more logical order in the language selector drop-down.
N/A
=> Alphabetize the Realm languages

snooty/rstspec.toml
[DOCSP-39650](https://jira.mongodb.org/browse/DOCSP-39650)
=> DOCS{-39650 Add atlas admin api to the language dropdown

snooty/rstspec.toml
DOP-4663
- Removes the `topic` directive as it is no longer used.
=> :fire: DOP-4663 removes the topic directive

snooty/rstspec.toml
DOP-4663
- Removes the topic directive for the `latest` branch as well.
=> DOP-4663 for latest

snooty/rstspec.toml
DOP-4758
- Merge changes from `latest` branch into `main` branch. This will allow tagged versions to have the updated rstspec changes, starting with next tag
=> DOP-4758: consolidate rstspec from latest to main

snooty/parser.py, snooty/rstspec.toml, snooty/test_parser.py
=> DOP-4647: Deleting unused Landing components

snooty/rstspec.toml
DOP-4947
Create a gold role (much like the red role)
Snooty PR upcoming for component.
=> DOP-4947: Add Gold role

snooty/rstspec.toml, snooty/test_parser.py
DOP-5059
Partner PR in Snooty [here](https://github.com/mongodb/snooty/pull/1276)
=> DOP-5059: Add `expanded` option to Collapsibles

snooty/rstspec.toml
DOP-5061
Sister PR in Snooty has staging
=> DOP-5061: Add title to options for Procedures

snooty/rstspec.toml
[DOCSP-45603](https://jira.mongodb.org/browse/DOCSP-45603)
Updates Search playground snapshot URLs
=> DOCSP-45603 Update Search playground snapshot URLs

snooty/rstspec.toml
DOCSP-46042
Added a new role since we're using it a bunch on [this Atlas page](https://github.com/10gen/docs-ops-manager/pull/634/files). I didn't want to update the existing one because other docs teams are still using it to track metrics.
=> DOCSP-46042 added a new role for downloads page

snooty/main.py, snooty/parser.py
=> fix: add ability to specify branch for Netlify

snooty/rstspec.toml
* This was incoming [Slack request](https://mongodb.slack.com/archives/C018UTGP23T/p1739389445600329) to fix the role destination.
=> Fix ak8so role

snooty/rstspec.toml
https://jira.mongodb.org/browse/DOCSP-48307
Adds a new role for window functions, which we will use to help distinguish between window functions and other aggregation expressions.
=> DOCSP-48307 Add role for window functions

snooty/rstspec.toml
DOP-5615
- See [UAT spreadsheet](https://docs.google.com/spreadsheets/d/1NLHTV6MVd3fscU1LQyr-9gCs2yS91rDBYWwMLo_T6fA/edit?gid=0#gid=0) (row 6) for reported bug.
- The list comes from this [Usage Guidelines](https://docs.google.com/document/d/1ZJ1SC1JrkUvUW0Y1dVeXntnC6Ix1PMhNrDPsONp5AxU/edit?tab=t.0)
=> DOP-5615: add options to composables

snooty/taxonomy.toml
(https://jira.mongodb.org/browse/DOCSP-50303
=> DOCSP-50303 updating taxonomy for new products
