mongodb/snooty-parser

snooty/gizaparser/test_steps.py, snooty/parser.py, snooty/rstparser.py, snooty/rstspec.toml, snooty/specparser.py, snooty/test_parser.py, snooty/test_specparser.py, stubs/docutils/nodes.pyi, stubs/docutils/parsers/rst/roles.pyi, stubs/docutils/parsers/rst/states.pyi
This PR retools how rst roles are handled, and categorizes them in three ways:
* `text` roles only provide a `label` field in the AST
* `explicit_title` roles provide a `target` field in the AST, as well as optionally a `label` field
* `link` roles do not emit a `role` node at all; instead, they emit a `reference` with the refuri already set.
=> DOCSP-5504: Only match PAT_EXPLICIT_TILE if needed by role

snooty/gizaparser/__init__.py, snooty/gizaparser/extracts.py, snooty/gizaparser/nodes.py, snooty/gizaparser/release.py, snooty/gizaparser/test_nodes.py, snooty/gizaparser/test_release.py, snooty/parser.py, test_data/extracts-test.yaml, test_data/release-base.yaml, test_data/release-specifications.yaml
*  Adds a ReleaseSpecificationsGizaCategory class
* Merges source_constants into the giza substitutions system
* Adds tests
* Raises a diagnostic upon use of undefined giza substitutions
This is a gentle breaking change: I think it's important for validation, but we use it in the corpus. So with this change, snooty logs a diagnostic, but replicates giza's behavior by inserting empty text.
=> DOCSP-5545: Implement release specifications

snooty/rstparser.py, snooty/rstspec.toml, snooty/test_parser.py, test_data/test_tabs.rst
With this change, tab nodes will provide the tabid in the `tabid` option, and the title if given in a directive_argument.
This is opposed to the old AST format where the argument could contain either a title or a tabid depending on whether the tabset was anonymous or not.
=> DOCSP-6493: Add missing tabid option to tab directive

HACKING.md, snooty/parser.py, snooty/rstparser.py, snooty/test_parser.py, snooty/test_types.py, snooty/types.py, test_data/bad_project/snooty.toml, test_data/test_project/snooty.toml
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6442)] Parse substitutions defined in the `snooty.toml` under `[substitutions]` and include their nodes in the AST.
=> DOCSP-6442: Parse repo-wide substitutions

snooty/rstparser.py, snooty/test_parser.py
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6504)] Both the numerical "version" argument (which appears on the same line as the directive) and the "explanation", which appears on the following line, are output as members of a node's `argument` array. Any subsequent indented directives are output as the node's children. I've already tested and verified that this output works on the front-end.
=> DOCSP-6504: Fix parsing of versionadded, versionchanged, and deprecated directives

snooty/parser.py, snooty/test_parser.py
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6620)] Handle `footnote` and `footnote_reference` directives by providing the relevant `id` and `refname` properties (as generated by Docutils) to the front-end. The front-end will be responsible for identifying `footnote_reference` nodes associated with a given `footnote`, as well as generating the numerical labels.
=> DOCSP-6620: Add footnote support

snooty/language_server.py, snooty/parser.py, snooty/test_util.py, snooty/util.py
[Jira ticket](https://jira.mongodb.org/browse/DOCSP-6805)
I refactored the process of converting the doc target name into its own util function `add_doc_target_ext()` to keep the logic consistent between the parser's doc target validation and the language server
=> DOCSP-6805: Doc links with dotted filenames are validated properly

snooty/parser.py, snooty/rstparser.py, snooty/test_parser.py
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6447)] Parse card group and upload associated images to `snooty.assets` collection.
=> DOCSP-6447: Parse card-group directive

snooty/parser.py, snooty/test_parser.py
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6885)] The MongoDB Manual successfully parses now.
=> DOCSP-6885: Fix footnote bug

CHANGELOG.md, snooty/main.py
[[JIRA](https://jira.mongodb.org/browse/DOCSP-6904)] The removal of suffixes from includes was causing filenames to be truncated if they contained a period (`.`). Now, don't remove suffix if the file is an extract.
=> DOCSP-6904: Fix truncated extracts

snooty/rstparser.py
Just noticed this typo while doing a code review. It's bothering me.
=> Fix the spelling of PAT_EXPLICIT_TITLE

snooty/parser.py, snooty/rstparser.py, snooty/test_parser.py
[[JIRA](https://jira.mongodb.org/browse/DOCSP-5819)] Properly parse toctree directives to prepare them for semantic parsing.
=> DOCSP-5819: Parse toctree directives

snooty/main.py
Fixes bug where PyMongo throws an error when using `$set` with an empty field:
```sh
pymongo.errors.WriteError: '$set' is empty. You must specify a field like so: {$set: {<field>: ...}}
```
=> Bugfix: Empty semantic parser dictionary

RPC-methods.md, snooty/language_server.py, snooty/main.py, snooty/parser.py, snooty/test_language_server.py, snooty/types.py, snooty/util.py
[JIRA Ticket](https://jira.mongodb.org/browse/DOCSP-7186)
This PR handles changes to the parser needed to retrieve the project name and fileid for pages being previewed via the Snooty extension.
Note: This must be pushed alongside the PR for the [frontend](https://github.com/mongodb/snooty/pull/118) before creating the formal PR for the VS Code extension.
=> DOCSP-7186: Implement RPC method to get project name

snooty/gizaparser/published_branches.py
In order to use GraphQL/optimize operations on the front end, save values not specified in `published_branches.yaml` as `null`. Previously, fields with no values specified were not included in documents on Atlas.
=> Bugfix: Save undefined values in published_branches.yaml as null in Atlas

snooty/semanticparser.py, snooty/test_semantic_parser.py
Save toctree nodes that lack children with an empty array, in accordance with the [spec](https://gist.github.com/sophstad/01e4265bdb0118b367adf6800f6d4ac4). This improves compatibility with the TOC React component.
=> Bugfix: Add empty array if toctree node lacks children

snooty/parser.py, snooty/test_language_server.py
[JIRA Ticket](https://jira.mongodb.org/browse/DOCSP-6887)
This PR changes the way figure nodes are handled before returning the page AST to Snooty on VS Code. The AST will now return figure nodes with values including their full path of the image on the user's local machine.
This PR must be merged before the VS Code PR for [DOCSP-6887](https://github.com/mongodb/snooty-vscode/pull/8).
=> DOCSP-6887: Update figure value to full local path when returning AST

snooty/semanticparser.py, snooty/test_semantic_parser.py
Fixes bug where user-specified toctree titles were being overwritten. Now, check to see if a title has been set. If not, attempt to lookup the page title to use. Otherwise, assign title to `None`.
Bug identified in https://github.com/mongodb/docs-node/pull/4.
=> Bugfix: Don't overwrite toctree titles

snooty/main.py
Add `filename` (path from `source/` + extension) field to documents in the `documents` collection. This will allow the front-end to more easily identify pages by checking document extensions.
=> Add filename field to Snooty documents

CHANGELOG.md, snooty/semanticparser.py, snooty/test_semantic_parser.py, snooty/types.py, test_data/test_semantic_parser/snooty.toml
[[JIRA](https://jira.mongodb.org/browse/DOCSP-7573)] Add support for new `toc_landing_pages` variable in `snooty.toml`, which defines which pages will _not_ be rendered as drawers in the toctree. This information as stored as a `drawer` flag in an `options` object within each toctree node.
For conversion from legacy toolchain, move slugs listed under `config/sphinx_local.yaml`'s `nav_excluded` section to an array represented by `toc_landing_pages` in snooty.toml.
```yaml
nav_excluded:
- /drivers
- /drivers/c
- /drivers/cpp
- /drivers/csharp
- /drivers/go
- /drivers/erlang
- /drivers/node-js
- /drivers/perl
- /drivers/php
- /drivers/python
- /drivers/ruby
- /drivers/scala
- /tools
```
```toml
toc_landing_pages = [
"/drivers",
"/drivers/c",
"/drivers/cpp",
"/drivers/csharp",
"/drivers/go", …
```
=> DOCSP-7573: Add drawer flag to toctree

snooty/parser.py, snooty/semanticparser.py, snooty/test_semantic_parser.py, test_data/test_semantic_parser/source/includes/test.rst, test_data/test_semantic_parser/source/page4.txt
[[JIRA](https://jira.mongodb.org/browse/DOCSP-7939)] Process includes in semantic layer so that they are written to Atlas with the contents of their includes as `children` of include nodes.
=> DOCSP-7939: Replace includes in semantic parse layer

snooty/rstspec.toml
We're documenting some methods that don't exist in the 3.0 driver, so we'd like to point the node-api/node-docs roles to 3.3. Tweaking it myself seems like it would create less work for y'all.
=> points node-api and node-docs roles to the 3.3 docs

snooty/main.py, snooty/parser.py
Small refactor to remove a function that specially handles updating `publishedBranches` in the metadata collection. Uses the more generic `on_update_metadata()` instead.
=> Refactor published branches update

CHANGELOG.md, snooty/gizaparser/extracts.py, snooty/gizaparser/nodes.py, snooty/gizaparser/release.py, snooty/gizaparser/steps.py, snooty/gizaparser/test_extracts.py, snooty/gizaparser/test_release.py, snooty/gizaparser/test_steps.py, snooty/parser.py, snooty/rstspec.toml, snooty/test_project.py, snooty/test_types.py, snooty/test_util.py, snooty/types.py, test_data/get-preview/snooty.toml, test_data/get-preview/source/includes/extracts-test.yaml, test_data/get-preview/source/includes/release-pinning.yaml, test_data/get-preview/source/includes/steps-test.yaml, test_data/get-preview/source/index.txt
* `Page.output_filename` becomes non-Optional, and a `Page.create()` class method is added.
* All output filename hacking is removed.
* `GizaCategory.to_pages()` takes an additional source path parameter, and the page creation factory takes in an output filename, allowing each GizaCategory to specify its desired output filename.
=> DOCSP-8084: Improve yaml output_file handling

Makefile, snooty/gizaparser/test_steps.py, snooty/intersphinx.py, snooty/parser.py, snooty/rstparser.py, snooty/semanticparser.py, snooty/specparser.py, snooty/test_language_server.py, snooty/test_parser.py, snooty/test_semantic_parser.py, snooty/types.py, test_data/test_semantic_parser/source/index.txt, test_data/test_semantic_parser/source/refrole.txt
There's one big strawman AST structure change: `target` and `target_directive` are unified. So:
`<target ids=[...] uriref="...">`
becomes
`<target domain="..." name="..." target="..." uriref="...">`
and `target_directive` becomes regular `target`.
Let me know what you think of this idea.
There's also a caveat in that the following things won't work right:
* `option` (requires special parsing voodoo)
=> DOCSP-6657: Add local targets to the TargetDatabase

.github/workflows/test.yml, snooty/parser.py
We will need to unify pending tasks and postprocessing to work with
Python 3.8's macOS new default multiprocessing spawn mode.
=> DOCSP-7399: Temporarily remove multiprocessing

snooty/eventparser.py, snooty/main.py, snooty/parser.py, snooty/postprocess.py, snooty/test_devhub.py, snooty/test_legacy_guides.py, snooty/test_util.py, snooty/types.py, test_data/test_devhub/snooty.toml, test_data/test_devhub/source/includes/authors/lastname-firstname.rst, test_data/test_devhub/source/index.txt
[[JIRA](https://jira.mongodb.org/browse/DOCSP-8727)]
- Move event parser classes into new file (`eventparser.py`)
- Add new `PAGE_EXIT_EVENT`
- Add new `DevhubPostprocessor` class, to be used when `default_domain = "devhub"` in snooty.toml
- In `DevhubPostprocessor`, expose specified directives via a new field in the `Page` class: `query_fields`
- `query_fields` is a top-level field on each page document and contains a nested document
- Fields exposed (listed as `field: data type`):
- `author`: string
- `tags`: list of strings
- `languages`: list of strings
- `products`: list of strings
- Will be queryable via Stitch
- `test_legacy_guides.py`
- Usual flakiness in `test_postprocess:test_expand_includes()`
=> DOCSP-8727: Postprocess queryable nodes

snooty/postprocess.py, snooty/test_devhub.py, snooty/types.py, test_data/test_devhub/snooty.toml
This adds an optional `pageGroups` field to the build metadata containing cleaned and validated page group slugs.
Example `snooty.toml` syntax:
```toml
[page_groups]
"Group 1" = ["index", "foo", "/page4"]
```
Example output field in the metadata document:
```json
"pageGroups" : {
"A Test Group" : [
"index",
"platforms",
"tutorial/getting-started-with-hadoop"
]
}
```
The careful reader will note that issues are logged rather than sent to the normal diagnostic mechanism: this is because our diagnostic mechanism doesn't currently handle snooty.toml issues properly (currently the vscode extension crashes), and I didn't want to make that problem any worse.
=> DOCSP-8731: Support page groups

snooty/language_server.py, snooty/main.py, snooty/parser.py, snooty/postprocess.py, snooty/test_language_server.py, snooty/test_project.py, snooty/types.py, snooty/util.py
I would like to have tests to ensure the URI returned is correct, but alas I couldn't figure out how to do that without increasing scope.
Basically, we store up diagnostics in the backend and let the language server decide when it's ready to pull them.
=> DOCSP-8389: Fix catch-22 in reporting config issues

snooty/postprocess.py, snooty/rstspec.toml
[[JIRA](https://jira.mongodb.org/browse/DOCSP-8848)] New directives:
- `devhub:updated-date`
- `devhub:callout`
Also exposes a few more fields from the AST based on conversations with Gregg.
=> DOCSP-8848: Add new devhub directives

snooty/postprocess.py, snooty/test_devhub.py, test_data/test_devhub/source/index.txt
Add preceding colon to directives outside the devhub domain so that they will be properly identified by the postprocess layer.
=> Bugfix: correctly target directives outside devhub domain

snooty/postprocess.py, snooty/test_devhub.py
The devhub front-end should have easy access to author names and images, not just names.
- Save `author` as an object with `name` and `image` fields for easy access to both.
- Save page slug in query_fields object
=> Expose devhub author images

snooty/postprocess.py, snooty/test_postprocess.py
Fixes a bug introduced by #108. To check for circular substitutions, a set was created to identify substitution reference nodes that had already been encountered. However, the check for duplicates was performed _every time_ a `substitution_replacement` node was encountered. Therefore, when a substitution was used more than once on a page, it was mistakenly identified as a circular substitution.
Now, only perform this check when looking at children of a `substitution_definition` node. Adds test to verify this behavior works (test currently fails on `master` branch).
=> Bugfix: Use substitution more than once on a page

snooty/rstspec.toml
Add a community forum role since there are many instances of this across the docs and the url may change at some point in the future.
https://jira.mongodb.org/browse/DOCSP-9371
=> DOCSP-9371 Related: add community forum role

snooty/rstspec.toml
Update to the directive for Java sync and async API docs.
=> Update Java API docs directive to point to new version (4.0)

snooty/rstspec.toml, snooty/test_devhub.py, test_data/test_devhub/source/index.txt
[[JIRA](https://jira.mongodb.org/browse/DOP-938)] Support for `image-alt` option.
=> DOP-938: Add image-alt to twitter directive

CHANGELOG.md, snooty/rstspec.toml
This adds the `spec` substitution from ecosystem extlinks.
=> Add spec extlink for ecosystem

snooty/parser.py, snooty/postprocess.py, snooty/test_devhub.py, snooty/test_language_server.py, snooty/test_parser.py, snooty/test_postprocess.py, test_data/test_postprocessor/source/folder/doc.txt
[[JIRA](https://jira.mongodb.org/browse/DOP-954)]
- Convert `:doc:` to `ref_role` in `JSONVisitor` class
- RefRoles with `name=doc` do not contain targets. We use targets on the front-end to navigate to a particular id (e.g. `/fileid#target`), so omitting this navigates to the root doc, as is expected behavior with `:doc:` roles. Let me know if this doesn't make sense!
- Doc refroles contain `fileid` properties to navigate to the correct page
=> DOP-954: Attach :doc: titles in postprocessor

snooty/main.py, snooty/test_postprocess.py, snooty/test_project.py
In order to have a successful rollout of patch-based builds, we'd like to have a period where the parser accepts the `--patch` flag, but does not actually write the `patch_id` field to the database. This PR accomplishes that and undoes some of the work of #138. Once the autobuilder Makefiles are properly implemented, we will attach `patch_id` to builds again.
=> DOP-948 update: Don't write patch_id to DB

snooty/rstspec.toml
Add support for two options to `list-table` directive:
- `align`
- `width`
Support is defined in the [documentation](https://docutils.sourceforge.io/docs/ref/rst/directives.html#list-table).
=> Add support for align & width option to list-table directive

snooty/postprocess.py, snooty/rstspec.toml, snooty/test_devhub.py, snooty/test_language_server.py, snooty/test_parser.py, snooty/test_postprocess.py
* Place `doc` in the `std` domain
* For each page top-level heading, create a target
=> Tweak :doc: role

snooty/test_postprocess.py, snooty/test_project.py, test_data/test_postprocessor/snooty.toml, test_data/test_project/snooty.toml
Update tests from https://github.com/mongodb/snooty-parser/pull/90. A project's `title` field as defined in `snooty.toml` does not belong in the `constants` table, so ensure we are properly testing it outside of this table.
=> Fix project title tests

snooty/gizaparser/published_branches.py, snooty/parser.py
I noticed I wrote a lot of redundant code for loading `published-branches.yaml` that was already handled in a more generic way for the various YAML files we deal with. Small refactor!
=> Improve published-branches.yaml code

snooty/main.py, snooty/test_postprocess.py, snooty/test_project.py
Implement what was undone in #145. Write patch ID (may be `None`) to the database.
=> Write patch ID to DB

snooty/intersphinx.py
Tested by feeding the inventory generated by ecosystem into cloud-docs, and confirming that it builds cleanly
=> DOP-1094: Add trailing newline to inventory to appease intermanual

snooty/diagnostics.py, snooty/gizaparser/parse.py, snooty/parser.py, snooty/rstparser.py, snooty/test_parser.py
Arguably we should be using an exception rather than multiple return values, but I really want this to go out with this release.
=> DOP-1135: Handle YAML parsing errors everywhere

CHANGELOG.md
CHANGELOG.md change for [DOP-876](https://jira.mongodb.org/browse/DOP-876), [PR 157](https://github.com/mongodb/snooty-parser/pull/157), was misleading. This fixes that.
=> DOP-876: Edit CHANGELOG.md for clarity

snooty/rstspec.toml
Adds examples to rstspec.toml so that we can generate a snippets file from those examples.
- Python script used to generate snippets file: https://gist.github.com/schmalliso/2144242ec50183c1b74441ac9da77117 This will obviously need to be adapted for automation purposes and to wrap it into the snooty-vscode extension.
- Jira ticket: https://jira.mongodb.org/browse/DOP-1133
1. Use the following python script to generate a snippets.json file (plopping in the relevant paths where paths are required): https://gist.github.com/schmalliso/2144242ec50183c1b74441ac9da77117
2. In VSCode, open the "Code" menu, then choose Preferences > User Snippets.
3. Type "RestructuredText" into the search box and choose {{restructuredtext.json}}. This will add sample snippets that will be available in files that …
=> DOP-1133: add snippets examples to all directive definitions

CHANGELOG.md, snooty/cache.py, snooty/eventparser.py, snooty/gizaparser/extracts.py, snooty/gizaparser/nodes.py, snooty/gizaparser/release.py, snooty/gizaparser/steps.py, snooty/gizaparser/test_extracts.py, snooty/gizaparser/test_release.py, snooty/gizaparser/test_steps.py, snooty/intersphinx.py, snooty/language_server.py, snooty/main.py, snooty/page.py, snooty/parser.py, snooty/performance_report.py, snooty/postprocess.py, snooty/rstparser.py, snooty/specparser.py, snooty/target_database.py, snooty/test_intersphinx.py, snooty/test_postprocess.py, snooty/test_project.py, snooty/test_types.py, snooty/types.py
Much refactoring was required to avoid circular import errors. This improves the overall code modularity, but makes this a bit bloated. Sorry!
Additionally, the spec is now a global, and is parsed upon specparser module import.
This is the resulting change in the output AST: https://github.com/mongodb/snooty-parser/pull/168/files#diff-915b6e0f0f3fa5b6662ec3cdccbee909R143
The specific example Jeff encountered is now output as:
```
{
"type": "ref_role",
"position": {
"start": {
"line": 107
}
},
"children": [
{
"type": "literal",
"position": {
"start": {
"line": 107
}
},
"children": [
{
"type": "text",
"position": {
"start": {
"line": 107
}
},
"value": "$match"
}
]
}
],
"domain": "mongodb",
"name": "pipeline",
"target": "pipe.$match",
"flag": "",
"url": …
```
=> DOP-1073: no longer render RefRole prefix if no title is found

CHANGELOG.md, snooty/n.py, snooty/parser.py, snooty/test_legacy_guides.py, snooty/test_parser.py
[[JIRA](https://jira.mongodb.org/browse/DOP-1129)] Add support for [all ordered list types supported by rST](https://docutils.sourceforge.io/docs/user/rst/quickstart.html).
=> DOP-1129: Handle additional ordered list types

snooty/rstspec.toml
We're standardizing on :doc:-style links for atlas. [DOP-1208](jira.mongodb.com/browse/DOP-1208) will sort out the content side for repos that are using the "wrong" format.
I have, uncharacteristically, run the tests.
=> DOP-1207: standardize on doc-format links for role.atlas

snooty/rstparser.py, snooty/rstspec.toml, snooty/test_parser.py, snooty/test_postprocess.py, test_data/test_postprocessor/source/a-program.txt, test_data/test_postprocessor/source/includes/test.rst, test_data/test_postprocessor/source/index.txt, test_data/test_postprocessor/source/page1.txt, test_data/test_postprocessor/source/page2.txt
[[JIRA](https://jira.mongodb.org/browse/DOP-1242)]
- Warn when deprecated directive is used, and include node in AST
- Remove default-domain directive from tests to avoid unintended diagnostic warnings (this had a waterfall effect on tests, sorry in advance!)
=> DOP-1242: Warn about deprecated directives

snooty/rstspec.toml
[[JIRA](https://jira.mongodb.org/browse/DOP-1243)]
- Deprecate `admonition`, `caution`, and `topic` admonition directives
- `see`, `seealso`, and `example` inherit the `admonition` directive config
- All admonitions (`note`, `important`, `warning`, `tip`, `see`, `seealso`, `example`) now accept titles because the [LeafyGreen component](https://mongodb.github.io/leafygreen-ui/?path=/story/callout--default) distinguishes between the title and the admonition type. Lemme know if I messed up the snippets!
**Note:** `danger` doesn't appear anywhere in docs content afaict, but it was included in rstspec.toml so I marked it as deprecated. We could delete it instead, though!
=> DOP-1243: Modify admonition configuration

snooty/parser.py, snooty/test_language_server.py, snooty/util.py
We add a `PageDatabase` class that handles storing both parsed and postprocessed pages, and ensures that they are properly differentiated. When the postprocessor is run, a full clone of all ASTs is performed to ensure that postprocessing is idempotent.
Performance report:
```
parse rst:     42.33
copy:     2.978
postprocessing:     13.07
serialization:     3.855
```
Cloning the AST adds 3-4 seconds to the server manual build that previously did not exist.
=> DOP-1282: Make postprocessor nondestructive

CHANGELOG.md, snooty/parser.py, snooty/test_parser.py
[JIRA.](https://jira.mongodb.org/browse/DOP-1269)
- Allow for additional delimiters for width options per the [rst list-table directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html#list-table).
- ` `
- `, `
-  `  `
- Test for these new options
=> DOP-1269: Allow for additional list-table width delimiters

snooty/eventparser.py, snooty/test_postprocess.py, test_data/test_postprocessor/source/note.txt
[[JIRA](https://jira.mongodb.org/browse/DOP-1320)] Include directive arguments in the postprocess iteration so that they can be postprocessed 😁 You can see it is fixed in this [staging link](https://docs-mongodbcom-staging.corp.mongodb.com/snooty-setup/cloud-docs/sophstad/DOP-1296/)!
=> DOP-1230: Postprocess directive arguments

snooty/rstspec.toml
[JIRA](https://jira.mongodb.org/browse/DOP-1337)
[Spec](https://docs.google.com/document/d/10TAxNOdWDp_vi-D_NTnA_YDQXLeyoPsFa2Banx1Srsw/edit#heading=h.tkooaeqt2p7i)
This PR simply adds a new directive to the rstSpec file for `search-results`. This directive takes no arguments.
Questions:
- Since this is a simple directive I was not sure if tests may be necessary, thoughts?
- Is the argument type correct? (I believe None is not defined in toml, but "none" works :) )
- Missing anything?
=> DOP-1337 Add search-results directive to rstspec

snooty/language_server.py, snooty/test_language_server.py
This addresses feedback that we received from Nic, and allows users of the vscode extension to filter out only snooty problems
=> Add missing source to LSP diagnostics

snooty/rstparser.py, snooty/rstspec.toml, snooty/test_parser.py, snooty/util.py
This also tweaks a warning's logic a bit: we actually check for a url before complaining about a url, matching Sphinx's logic
=> DOP-1429: Support alternative no-title ref_role syntax

snooty/postprocess.py, snooty/test_postprocess.py, test_data/test_postprocessor/source/page2.txt
[DOP-981] Standardize toctree `title` fields so that rather than mixing lists of text nodes and plain strings, all fields appear as a list of text nodes. Staged on Datalake for good measure and it looks [great](https://docs-mongodbcom-staging.corp.mongodb.com/master/datalake/sophstad/master/)!
=> DOP-981: Standardize toctree title nodes

snooty/diagnostics.py, snooty/postprocess.py, snooty/test_postprocess.py
Diagnostic message is, for example, `Ambiguous target: "std:term:something". Locations: reference/glossary, https://docs.mongodb.com/manual/reference/glossary`
=> DOP-1434: Explain ambiguous target choices

snooty/rstspec.toml
[DOP-1489] Support use of `:red:` without `.. role:: red`.
=> DOP-1489: Un-deprecate red role

snooty/diagnostics.py, snooty/parser.py, snooty/rstparser.py, snooty/test_parser.py
The change to `parser.py` is key. The docutils class hierarchy is confusing and strange.
=> DOP-1511: Correctly handle incorrect monospacing

snooty/rstspec.toml
This has a sibling PR that preps the Realm docs to match the updated config: https://github.com/mongodb/docs-realm/pull/491
https://jira.mongodb.org/browse/DOCSP-12508
- [mongodb_conf.py](https://github.com/mongodb/docs-tools/blob/master/sphinxext/mongodb_conf.py#L311)
- [conf.py](https://github.com/mongodb/docs-realm/blob/master/conf.py)
=> (DOCSP-12508): Centralize Realm extlink roles & custom directives

snooty/parser.py, snooty/postprocess.py, snooty/test_postprocess.py, snooty/util.py
This PR also copies all included ASTs upon inclusion, correcting the previous behavior.
This adds roughly 1.5s to the postprocessor, which is small but significant and repeatable for that stage taken on its own.
```
Before:
parse rst      40.20
copy           3.14
postprocessing 10.31 <-- Here
commit         0.00
serialization  3.74
After:
parse rst      38.71
copy           2.88
postprocessing 11.84 <-- Here
commit         0.00
serialization  3.54
```
=> DOP-1434: Automatically resolve ambiguous targets

snooty/rstparser.py, snooty/test_parser.py
This change scares me -- admonitions are a very gnarly and fragile part of docutils. We have a lot of test cases, but likely not every single situation a writer has ever come up with.
=> DOP-1523: Permit version admonitions to have no argument

snooty/diagnostics.py, snooty/main.py, snooty/rstparser.py, snooty/test_parser.py
Example output:
```
ERROR(includes/glossary-terms.rst:9ish): Malformed external link
Did you mean: `Atlas Data Lake <https://docs.mongodb.com/datalake/>`__
```
=> DOP-1570: Add simple "did you mean" feature

snooty/rstparser.py, snooty/rstspec.toml, snooty/specparser.py, snooty/test_parser.py
Make rstobject directive arguments required. Currently, the parser crashes if no argument is passed to a callable rstobject.
=> DOP-1589: Support required arguments

snooty/diagnostics.py, snooty/parser.py, snooty/rstparser.py, snooty/rstspec.toml, snooty/specparser.py, snooty/test_parser.py, snooty/util_test.py, test_data/test_tabs.rst
relevant ticket: https://jira.mongodb.org/browse/DOP-1450
The changes included in the PR are: 
1. adding tabset definitions in `rstspec.toml`
2. register these directives with `docutils` in `rstparser.py`
3. if an unknown tabset is given, raise a diagnostic in `handle_tabset` in `parser.py` 
4. add the appropriate title (via adding a <directive_argument> to named tabs in `handle_tabset`
5. If an unknown tab ID is given, raise a diagnostic in `handle_tabset`
6. finally, sort tabs according to their order in the tab definition in `handle_tabset`
=> DOP-1450: define and formally support tabs in rstspec.toml

snooty/rstparser.py, snooty/test_parser.py
Jira link: https://jira.mongodb.org/browse/DOP-1581
- extlinks will use the 'target' for the label if no label is set
- handles special case for `:rfc:`, where we'd ideally like the label to be `RFC-123465` rather than just `123465`. This brings parity to sphinx's built-in rfc role and will generally behave the way writers expect it to.
It is entirely possible that there's an easier way to know what role we're parsing, but I couldn't figure it out, so this was my solution 😁
=> DOP-1581: extlinks should use target for label if no label set *not* the uri

Makefile, snooty/test_language_server.py
* Skip test_debounce() in CI: flaky and timing-sensitive
* Run tests in Python Development Mode (https://docs.python.org/3/library/devmode.html)
=> Improve CI workflow

snooty/parser.py, snooty/test_parser.py
[DOP-1632] Fix sorting of tabs by using key of tabids directly from `rstspec.toml`.
=> DOP-1632: Fix tab sort

snooty/rstspec.toml
JIRA:
https://jira.mongodb.org/browse/DOCSP-12335
=> DOCSP-12335: bump node version

snooty/diagnostics.py, snooty/postprocess.py, snooty/test_postprocess.py
Fixes bug where previously encountered tabsets would be overwritten if the page included multiple `tabs-pillstrip` or `tabs-selector` directives.
=> DOP-1526: Fix double tabs-pillstrip bug

snooty/diagnostics.py, snooty/parser.py, snooty/test_diagnostic.py, snooty/test_parser.py
[DOP-277] When an unexpected indentation is encountered, provide a more helpful error message by suggesting use of the `.. blockquote::` directive via `MakeCorrectionMixin`.
=> DOP-277: Suggest blockquote directive when unexpected indentation is encountered

snooty/rstparser.py, snooty/test_postprocess.py, snooty/test_postprocess_old_and_monolithic.py
For rstobjects with type `specparser.TargetType.cmdline_option` (only std:option right now), if no label is given, just use the original target name as written for the label instead of looking it up during postprocess.
=> DOP-1675: Don't include binary name unless requested in :option: links

snooty/parser.py
On Unix the result should be essentially the same (except that `getpass.getuser()` respects environment variables), but `getpass` is portable to other platforms.
=> Remove usage of unportable 'pwd' module

snooty/test_parser.py
Reduces number of spaces from 4 to 3 in `test_toctree()`
=> Fix test_toctree() spacing

snooty/rstparser.py, snooty/test_parser.py
[DOP-1750] We weren't correctly handling the case where `:copyable: true` was explicitly specified. Fix that!
=> DOP-1750: Fix :copyable: true handling

pyproject.toml
Recently, the `watchdog` package dropped its compatibility of older Python (version<3.6) and update the big version number of itself. This cause a problem that someway if you want to use `snooty` with Python (version>=3.7), you'll get an error like below:
```
Collecting watchdog~=0.10.3
Using cached https://pypi.python.org/packages/.../watchdog-0.10.5.tar.gz (99 kB)
ERROR: Package 'watchdog' requires a different Python: 3.8.5 not in '>=2.7, <3.6'
```
See also: 
https://github.com/vscode-restructuredtext/vscode-restructuredtext/issues/257
https://github.com/pypa/pip/issues/9121#issuecomment-745893622
The change of `watchdog` doesn't affect `snooty` since both of them support Python 3.7+, and `make clean && make test` is also passed with Python 3.8.5 on Linux.
=> fix watchdog dependency with updating correct version number

snooty/gizaparser/nodes.py, snooty/gizaparser/test_nodes.py, snooty/gizaparser/test_steps.py
Perform substitutions when reifying rather than while inheriting, and only in the top-most `reify()` call.
=> DOP-1875: Fix altering giza substitutions in inheriting nodes

snooty/builders/man.py, snooty/gizaparser/test_steps.py, snooty/n.py, snooty/parser.py, snooty/postprocess.py, snooty/test_postprocess.py
[DOP-1857] Allow references/links defined with only a single underscore to be reused by name elsewhere in the corpus.
=> DOP-1857: Allow "reusable" references

snooty/rstspec.toml
This bumps the api link version to 4.2. In addition,
it adds Rust as a valid driver tab. Lastly, it adds
the java driver-core api ref.
=> chore: bump versions, add Rust tab, add java-core

snooty/postprocess.py, snooty/test_postprocess.py
[[JIRA]](https://jira.mongodb.org/browse/DOP-1931). 
Docs are staged with the following added to the toctree: `Overview </index>`
[[Compass]](https://docs-mongodbcom-staging.corp.mongodb.com/master/compass/cgoecknerwald/master/).
[[BI-Connector]](https://docs-mongodbcom-staging.corp.mongodb.com/master/bi-connector/cgoecknerwald/master/).
=> DOP-1931: Modify the toctree handling so that index.txt can add itself to the toctree with RecursionError

snooty/rstspec.toml
@nlarew Turns out we have a lovely redirect chain when crawling the Realm pages because we're linking to the wrong root URL for the Kotlin docs (from here: https://github.com/realm/realm-java/blob/1cfe291f90d1ce5c58a1ab9b44e41c225ee9f8e7/build.gradle#L238).
This will point us at the actual root folder, which will get rid of some of the jumps that we have to crawl to index the pages, apparently. If you could review, I'd be most obliged! This is only used once in the realm docs, for the TOC.
=> DOP-1883: update URL of kotlin SDK to avoid redirect chain

snooty/postprocess.py, snooty/test_postprocess.py
[DOP-2045] Currently, the front end handles parsing the heading nodes that should appear in the "On this page" box. This has degraded performance of the component, as this operation is fairly expensive and really belongs in the parser. So, this PR adds that logic to the postprocess layer.
- Identify heading nodes up to _n_ specified by `:depth:`; if `:depth:` option is omitted, include all heading nodes in accordance with [docutils](https://docutils.sourceforge.io/0.4/docs/ref/rst/directives.html#table-of-contents).
- Save list of headings to `headings` field in page options
=> DOP-2045: Identify headings for 'On this page' box

snooty/rstspec.toml, snooty/test_landing.py, test_data/test_landing/source/index.txt
The button `class` option is [no longer necessary](https://github.com/mongodb/snooty/pull/374/files) - remove it + standardize quotes in the landing domain.
=> rm-button-class: Remove button class option + standardize quotes

snooty/rstspec.toml
This directive should be removed once we implement a proper new way of doing this.
=> DOP-2088: Temporarily un-deprecate directive.class

snooty/diagnostics.py, snooty/postprocess.py, snooty/rstspec.toml, snooty/test_postprocess.py, snooty/test_postprocess_old_and_monolithic.py, snooty/util_test.py
- Add support for `ia` and `entry` directives
- Save their contents to page-level options, as well as to a sitewide `iatree` entry in the `metadata` document
- If `iatree` exists, use it to generate breadcrumbs and in-order traversal of site (i.e. have it replace `toctree`)
- Add new new testing util, `check_toctree_testing_string()`, which uses an approach similar to `check_ast_testing_string()` to enable tests that are more legible than a direct dict comparison
- Convert existing tests to use function
=> DOP-2055: Add IA support

snooty/rstspec.toml
Adds `extra-compact` card group style to support card groups that appear on pages in docs-landing ([see InVision](https://mongodb.invisionapp.com/console/share/3EZ68OEPSKB/587712512)). For example:
Am very open to renaming this! I went with "extra-compact" because these cards use the same layout as `compact` but the icons are even smaller.
=> DOP-1836: Add extra-compact card-group style

snooty/diagnostics.py, snooty/parser.py, snooty/test_parser.py, snooty/test_postprocess.py, test_data/test_tabs.rst
**Story**
https://jira.mongodb.org/browse/DOP-1878
**Notes**
- Adds a tab children validator for any `tabs` directive, ala the child validation logic for `tabsets`
- Alters copy of existing `tabset` warning
=> Dop 1878: Validation for children within ::tabs

snooty/intersphinx.py, snooty/rstspec.toml
Updates intersphinx parse so that it correctly matches `:py:meth:` (the sphinx-recommended syntax) to `py:method` as described in the intersphinx inventories. Adds the mongodb domain to the `phpmethod` and `phpclass` roles so that those intersphinx links work.
To repro:
1. build server docs on prod snooty-parser note that there will be target not found errors for motor, pymongo and phplibrary
2. delete your ~/.cache/snooty folder
3. build the server docs using this PR's version of snooty-parser and notice those errors are GONE
4. rejoice!
=> DOP-1810: fix handling of pymongo, motor, and phplib links

Makefile
Useful for trying out alternative python implementations, e.g. `make test SYSTEM_PYTHON=$(which pyston)`
=> Use the specified Python when creating a venv

snooty/rstspec.toml, snooty/test_landing.py, test_data/test_landing/source/index.txt
[JIRA](https://jira.mongodb.org/browse/DOP-2117).
Currently, CardGroup layout is determined by the Card `style` option. For example, if `compact` is specified as a card style, the card layout will stack (rather than carousel) on mobile. This PR differentiates these two functions by adding a `layout` option to CardGroup.
Cards should "stack" vertically on mobile screens as the default option (currently used on Product Landing Pages). Writers should be able to specify 'carousel' to have cards carousel on mobile screens as a non-standard option. (See: [docs-landing](https://docs.mongodb.com) on mobile).
Expected benefits: no weird layout side effects when specifying Card `style`, ability to support new `layout`s in the future
=> DOP-2117: Add layout option to landing Cards

snooty/rstspec.toml
[DOP-2174](https://jira.mongodb.org/browse/DOP-2174).
Add card-tag role to represent the Realm landing page's [new Card tag components](https://www.figma.com/file/hPTwMb9uHOypYLckYDg072/Realm-PLP?node-id=0%3A1) (see: `Android ->`, `iOS ->`, etc). We expect the following rST:
```
.. card::
:options: blah
Card text.
:card-tag:`Android <android-intro>`
```
=> DOP-2174: Add card-tag refrole

snooty/parser.py, snooty/test_parser.py
docutils replaces escape characters with \x00. Our two options
are to either monkey-patch docutils to prevent that (risky, brittle),
or we can undo this once we ingest docutils output.
docutils provides an unescape() function, but it does a lot of things
based on input parameters, and let's just not play that game.
=> DOP-2196: Remove \x00 characters from text nodes

snooty/eventparser.py
* Usage of `*args` and `**kwargs` turned out to be expensive
* Remove unnecessary set construction and string mutation on every node notification
* Some unnecessary class removal and method inlining (mainly for readability but I saw small performance bumps)
Time of `before/after`:
CPython 3.9.5: 56% of the time of prior
Pyston 2.2.0: 49% of the time of prior
```
$ git checkout master; make clean; make performance-report SYSTEM_PYTHON=python3 | grep postprocessing
postprocessing 8.81
```
```
$ git checkout fleet-fox; make clean; make performance-report SYSTEM_PYTHON=python3 | grep postprocessing
postprocessing 4.91
```
```
$ git checkout master; make clean; make performance-report SYSTEM_PYTHON=pyston | grep postprocessing
postprocessing 6.10
```
```
$ git checkout fleet-fox; make clean; …
```
=> Optimize eventparser.py

snooty/rstspec.toml
Hi Docs Platform Team. My name is Alek Binion and I am a member of the DevEd DBX team. I am hoping to add the following directives to snooty parse. Please let me know if my putting in this PR is helpful, or in the future you would rather I just submit a ticket. 
JIRA Ticket : [DOP-2223](https://jira.mongodb.org/browse/DOP-2223)
=> DOP-2223: Add versioned node-api directives

snooty/rstspec.toml
I did not realize before that the previous naming conventions of the new `node-api` roles would cause things to break. Added quotes to prevent this issue.
=> DOP-2223: Fix names for node-api roles

snooty/gizaparser/steps.py, snooty/gizaparser/test_steps.py, snooty/test_language_server.py, snooty/test_project.py
[DOP-2249](https://jira.mongodb.org/browse/DOP-2249). 
[Relevant frontend PR](https://github.com/mongodb/snooty/compare/DOP-2249).
Broke into a separate ticket to reduce bulk of the [landing-domain overhaul PR](https://github.com/mongodb/snooty-parser/pull/314).
This ticket aims to differentiate YAML-generated versus rST-generated `step`/`steps` in the parser. (rST step/steps directives forthcoming.)
[Realm staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/realm/cgoecknerwald/DOP-2249/sdk/ios/install/), [Realm live](https://docs.mongodb.com/realm/sdk/ios/install/), [rST](https://github.com/mongodb/docs-realm/blob/master/source/sdk/ios/install.txt#L50)
=> DOP-2249: Add -yaml tag to YAML-generated steps

snooty/rstspec.toml
These directives were removed in 1864c69 but have some trailing uses - this changeset restores them.
=> Patch: restore hlist & blockquote

snooty/postprocess.py
Each pass is moved into its own class with strict event handler naming,
and shared state is made explicit. Passes can refer to each other via
a Context object.
The intent of this is to make reading the file and determining data flow
easier.
Every handler now is a subclass of Handler with four overridable methods:
* enter_node()
* exit_node()
* enter_page()
* exit_page()
The postprocessor can then just define all of its handlers and how they should be run as a class variable: `Postprocessor.PASSES`.
=> Refactor postprocessor.py

snooty/rstspec.toml
Adds "5.0" as a valid version for the `mongo-web-shell` directive.
=> DOP-2356: Add version 5.0 to mongo-web-shell directive

pyproject.toml
Broaden `networkx` dependency to all compatible releases, without using flit's unsupported "Compatible with version" semver operator (#327).
=> Broaden networkx dependency

snooty/builders/man.py, snooty/parser.py, snooty/test_postprocess.py, snooty/util_test.py
The bug observed was caused by us popping the parent Paragraph node, but continuing to call `handle_departure()` for it causing a double state-pop.
Adding an assertion in list construction also caught a somewhat obscure issue where a `snooty_diagnostic` docutils node would also cause an undesired state pop.
There were also escaping issues in `ast_to_testing_string()` causing a test failure. It would be nice to use a proper XML generator rather than... this.
=> DOP-2424: Fix substitution lifting

snooty/rstspec.toml, snooty/test_postprocess.py
Updates tab drivers reference "Mongo Shell" to "MongoDB Shell"
[SHE-RA](https://jira.mongodb.org/browse/DOP-2332) 🦸‍♀️
[Docs staging](https://docs-mongodbcom-staging.corp.mongodb.com/master/docs/cgoecknerwald/master/tutorial/insert-documents/)
=> DOP-2332: tab drivers Mongo Shell -> MongoDB Shell

snooty/diagnostics.py, snooty/postprocess.py, snooty/rstspec.toml, snooty/test_postprocess.py
DOP-2443
This PR adds the new `chapters`, `chapter`, and `guide` directive to the parser. A new handler has been added to the postprocessor to take care of all guides and chapters to construct their metadata. Metadata for individual guides that include their time and descriptions will be added in a separate PR.
=> DOP-2443: Implement Chapters on the postprocessor

snooty/rstspec.toml
[DOP-929](https://jira.mongodb.org/browse/DOP-929) hands functionality back to writers on `docs-ecosystem/source/index.txt`. As part of this tech debt, we are also standardizing `ecosystem` to `drivers`, and `homepage` to `index`, as reflected here.
Rather than having a standalone `ecosystem` domain, I thought it prudent to merge this into the larger `mongodb` domain on the thought that this page may need to include other directives within the `mongodb` domain in the future.
This directive is currently not being used (at least not until the [docs-ecosystem PR](https://github.com/mongodb/docs-ecosystem/pull/766) goes out), so this change will not have any impact.
=> DOP-929: Update directive to mongodb:drivers-index-tiles

snooty/parser.py, snooty/test_parser.py, snooty/test_postprocess.py
While working on DOP-2446 on the frontend ([PR](https://github.com/mongodb/snooty/pull/508)), I realized that the chapter's image wasn't being saved/uploaded onto the database. This PR fixes this issue while also consolidating the same logic for validating images into a reusable function.
Here is a staging link to confirm that the images are validated and parsed properly:
[Guides Staging](https://docs-mongodborg-staging.corp.mongodb.com/test-guides/guides/raymundrodriguez/DOP-2446/)
=> DOP-2446: Validate and save chapter image asset

snooty/parser.py, snooty/postprocess.py, snooty/rstspec.toml, snooty/test_postprocess.py
[Related frontend PR](https://github.com/mongodb/snooty/pull/511)
[Frontend staging link](https://docs-mongodbcom-staging.corp.mongodb.com/test-guides/guides/raymundrodriguez/DOP-2447/)
This PR adds the `icons` option to the `chapter` directive. Each guide of a particular chapter will include that same `icon` in the guides site homepage. An example can be seen on the staging link, under "Gallery View".
=> DOP-2447: Add icons to chapters

snooty/parser.py, snooty/util.py, snooty/util_test.py
It seemed to be caused by issues around our observer API, so we make the
following changes:
* Disable filesystem watching in tests
* Open the project in a context manager as intended, although this has
no real effect due to the previous change
* Add a big lock to the FileWatcher, just to be safe
=> Fix an intermittent test failure

snooty/parser.py, snooty/rstspec.toml, snooty/test_openapi.py
[Frontend Staging Link](https://docs-mongodbcom-staging.corp.mongodb.com/test-openapi/cloud-docs/raymundrodriguez/DOP-2533/reference/api/openapi/)
[Associated frontend PR](https://github.com/mongodb/snooty/pull/512) - to be merged together with this PR.
The purpose of this PR is to allow the `openapi` directive to accept an argument that acts as a key for the frontend to call a Realm function with. 
Additionally, using the `openapi` directive with a url as an argument has been updated such that the contents of the remote file will be saved as a JSON string. This is to prevent the frontend from running into CORS errors from urls that don't have the right access configuration.
=> DOP-2533: Support using Realm to fetch OpenAPI specs for the frontend

snooty/postprocess.py
We want to give chapters html5 IDs so that anchor tags will be able to refer to these chapters on the page. I decided to bundle this in with DOP-2505, but is mostly prep work for a future ticket.
=> DOP-2505: Give html5 id to chapter

snooty/target_database.py
Legacy's intersphinx implementation is doing some escaping in one specific case. We should look into what intersphinx is actually doing, but this solves the immediate resolution problem.
=> DOP-2636: Temporary workaround for intersphinx escaping issues

snooty/rstspec.toml, snooty/test_parser.py
This change modifies the `cta-banner` directive to allow it to take an LG icon as an option, so that other LG icons can be used if needed. The default icon if none is specified is the "Play" icon. 
[DOP-2719 JIRA Ticket](https://jira.mongodb.org/browse/DOP-2719)
=> DOP-2719: Generalize cta-banner icon option

snooty/rstspec.toml
This change adds a visibility option to the output directive, which allows writers to specify whether or not they would like the output code snippet to be visible or hidden on default.
=> DOP-2760: Add visibility option to output directive

snooty/rstspec.toml
This new directive takes in a video URL to be embedded within the docs.
=> DOP-2754: Add video directive for video embeddings

snooty/rstspec.toml
[DOP-2742](https://jira.mongodb.org/browse/DOP-2742)
=> DOP-2742: Restore examples for io-code-block, input, and output directives in rstspec.toml

snooty/rstspec.toml
Already been renamed in the documentation content -- just need to fix it here.
=> Rename "Android SDK" tab to "Java SDK"

snooty/builders/man.py, snooty/builders/test_man.py, snooty/eventparser.py, snooty/gizaparser/parse.py, snooty/gizaparser/test_extracts.py, snooty/gizaparser/test_steps.py, snooty/language_server.py, snooty/main.py, snooty/page.py, snooty/parser.py, snooty/postprocess.py, snooty/target_database.py, snooty/test_devhub.py, snooty/test_intersphinx.py, snooty/test_language_server.py, snooty/test_main.py, snooty/test_mongodb_domain.py, snooty/test_postprocess.py, snooty/test_postprocess_old_and_monolithic.py, snooty/test_project.py, snooty/test_sharedinclude.py, snooty/test_types.py, snooty/types.py, snooty/util.py, snooty/util_test.py
A Long Time Ago we moved where FileId and SerializableType lived to avoid a cyclic import. Let's tidy up the compatibility re-exporting to avoid *another* cyclic import.
=> Unravel reexporting spaghetti

pyproject.toml, snooty/main.py, snooty/rstspec.toml, snooty/specparser.py, snooty/test_project.py, snooty/types.py
This permits `rstspec.toml` to list fields that may be included in `snooty.toml` under the `data` namespace. This is to be used for Nathan's asset fetching script.
=> DOP-2657: Add data_fields

snooty/rstspec.toml
Ticket: DOP-2939
[Staging link](https://docs-mongodbcom-integration.corp.mongodb.com/DOP-2939/datalake/raymundrodriguez/master/reference/cli/collections/create-collections-views/) - see list of `store` examples at the top of the page
=> DOP-2939: Add rstobjects for Data Lake config

snooty/rstspec.toml
[JIRA](https://jira.mongodb.org/browse/DOCSP-22934)
=> DOCSP-22934: add link roles to atlas openapi spec

snooty/diagnostics.py, snooty/parser.py, snooty/test_parser.py, snooty/test_util.py, snooty/util.py
[DOP-3064](https://jira.mongodb.org/browse/DOP-3064)
[DOP-3039](https://jira.mongodb.org/browse/DOP-3039) added support for relative URLs in the `Card` component in the frontend. This PR adds validations to the parser to ensure that any relative URL passed as an option to the card directive points to a valid `.txt` file within the docs site being parsed.
The relative URLs can have leading or trailing slashes (or no slashes at all if the referenced file is not nested within the `source` directory). This aligns with the [expectations in the frontend](https://github.com/mongodb/snooty/blob/f57d8464374d62808a822d1cbeab6bb65d538ec9/tests/unit/Card.test.js#L20).
**Current Behavior**:
Running the parser when an invalid relative URL is passed in the card directive does not generate an error. …
=> DOP-3064: Validate relative URLs in card directives

snooty/parser.py, snooty/test_parser.py
[improvements to icon validation](https://jira.mongodb.org/browse/DOP-1166)
previous solution: only checking :icon: role, and also has possibility of letting non existent icon targets to slip by since we are constructing a set of possible classnames
update: explicitly come up with icon classname from role name and target name, and validate this icon classname in set of valid icon classnames
=> DOP-1166: include all icon roles. parse icon classname from role + target

snooty/postprocess.py, snooty/test_postprocess.py, snooty/test_types.py, snooty/types.py, test_data/test_postprocessor/snooty.toml, test_data/test_project/snooty.toml
See acceptance criteria from [DOP-3197](https://jira.mongodb.org/browse/DOP-3197)
- parser supports associated_products entry in snooty.toml
- persisted into metadata output
- accessible within project_config within parser's lifecycle
=> DOP-3197: persist associated_products from snooty.toml

snooty/diagnostics.py, snooty/main.py, snooty/postprocess.py, snooty/target_database.py, snooty/test_intersphinx.py, snooty/test_util.py, snooty/util.py
Implement Damerau-Levenshtein Distance spelling suggestions, with an edit distance of 2. Heuristics are used to severely limit the amount of entries in the target database we actually have to check, so even with large (non-adversarial) target databases this has low overhead.
However, each call is quite slow, so a pathological database could chew up a lot of time. It could be worth terminating if a set amount of time is wasted, and it might behoove us to copy the list of keys to check and release the lock quickly.
Example error:
```
ERROR(includes/steps-change-replica-set-wiredtiger.yaml:0ish): Target not found: "label:4.2-mmapv1-conf-option"
Did you mean: std:label:4.2-mmapv1-conf-options
```
It would be better if the `did you mean` string were less... implementation-y and gave proper …
=> Spelling suggestions for linking targets

snooty/types.py
With this change the build for DOP-3320 of docs-tutorials would have yielded the following error:
```
ERROR(snooty.toml:0ish): Unmarshalling Error: Incorrect type. Got ['https://www.mongodb.com/docs/manual/objects.inv', 'https://pymongo.readthedocs.io/en/stable/objects.inv', 'https://motor.readthedocs.io/en/stable/objects.inv', 'https://www.mongodb.com/docs/atlas/objects.inv', 'https://www.mongodb.com/docs/php-library/master/objects.inv', 'https://www.mongodb.com/docs/compass/current/objects.inv', 'https://www.mongodb.com/docs/database-tools/objects.inv', 'https://www.mongodb.com/docs/drivers/node/master/objects.inv', 'https://www.mongodb.com/docs/drivers/go/master/objects.inv', 'https://www.mongodb.com/docs/drivers/java/sync/master/objects.inv', …
```
=> DOP-3320: Tighten up snooty.toml constants type definition

.github/workflows/test.yml, Makefile
* [set-output is now deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
* actions/setup-python@v2 is using a deprecated version of node, and is now v4
* actions/upload-artifact@v1 uses the deprecated set-output stanza
* actions/checkout is now v3
=> Update GitHub actions

HACKING.md
[DOP-3159](https://jira.mongodb.org/browse/DOP-3159)
- update parser readme
- include details for prerequisites and steps to install
- include details for granular components
- include expected input of AST
- minor additions to add intention of packages
=> DOP-3159: README overhaul

snooty/postprocess.py, snooty/test_postprocess.py
DOP-3353
* It's more convenient to have the spec file's actual content as a string within the metadata. Since the parser layer already handles grabbing the content and turning it into a string, all the postprocessor has to do is grab it. This also avoids having to re-read the spec files across more than one of our tools (limiting it to the parser).
=> DOP-3353: Change OpenAPI metadata source to be spec string

snooty/postprocess.py, snooty/test_postprocess.py
Named references should be scoped to a single .txt file to prevent namespace collisions and general undefined behavior.
This will require a fix in the [server manual](https://github.com/10gen/docs-mongodb-internal/blob/a4a305fd467fe00ace6e2ffd4ac266109a0e7055/source/release-notes/5.1-compatibility.txt) for the `MongoDB Enterprise` named reference
=> Have a separate Named Reference mapping for each .txt context

.github/workflows/release.yml, .github/workflows/test.yml, pyproject.toml
This PR splits the CI and Release tasks into two different actions: `CI` runs on `(macOS-x86-64,Linux-x86-64) X py3.8,py3.11)`, while `Release` runs on `(macOS-x86-64,Linux-x86-64) X py3.11)`
On my laptop (i7-1065G7, 4 cores), this results in a 14% reduction in time building 10gen/docs-mongodb-internal#888fad61c726440d07de6f399cec6da925156c75: 41.263s down to 35.496s, lowest time of 3 runs
=> DOP-3298: Upgrade release Python to 3.11

snooty/postprocess.py
**Goal**: associated ToC nodes should have `children[]` and `slug` fields for front end consumption, pre-persistence module invocation.
these missing attributes lead to front end bugs, ie. missing children in node, missing slug field for link
tested with [test branch for cloud docs](https://github.com/10gen/cloud-docs/blob/DOP-3382-toc/source/index.txt#L205)
pre change:
```
{
"title": [
{
"type": "text",
"position": {
"start": {
"line": {
"$numberInt": "0"
}
}
},
"value": "Atlas CLI"
}
],
"options": {
"project": "atlas-cli"
}
}
```
post change:
```
{
"title": [
{
"type": "text",
"position": {
"start": {
"line": {
"$numberInt": "0"
}
}
},
"value": "Atlas CLI"
}
],
"options": {
"project": "atlas-cli"
},
"children": [],
"slug": "atlas-cli"
},
```
=> DOP-3436: associated ToC missing children/slug

pyproject.toml
This permits very slightly faster installation.
=> Bump fett to use wheel

snooty/parser.py, snooty/test_parser.py
[DOP-3386](https://jira.mongodb.org/browse/DOP-3386)
----
The `copyable` option for code blocks is not being set when used as an option on a `literalinclude`. The conditional check for this option was based off of a string value rather than a boolean.
A/C: 
`Code` blocks will have the copyable option propagated on `literalinclude` by default, but also when:
- docs writers set `:copyable: true` as an option on the `literalinclude`
- as a fallback, when docs writers set `:copyable:` without a boolean
This PR also adds a test to ensure future adherence to this ability.
----
**Example from parser run:**
When parsing this rst:
```
.. literalinclude:: /includes/tutorials/change-streams/output/change.json
:language: json
:copyable: true
:emphasize-lines: 5
```
----
The master branch allows the …
=> DOP-3386: fix literalinclude copyable option

snooty/diagnostics.py, snooty/postprocess.py, snooty/test_postprocess.py
[DOP-3211](https://jira.mongodb.org/browse/DOP-3211)
Creating a `reference` that doesn't precede a heading and then attempts to `reference` that target without providing a label does not emit an error. It successfully builds, but the `ref` has no children to render, leaving the user with a visually empty spot where a link should be.
Through my investigation I found many instances of this stemming from the one bug report. As many as eleven invisible refs in `docs-mongodb-internal `alone. This error will help content writers to identify before production.
[Current site](https://www.mongodb.com/docs/v6.0/reference/)
- Above the text `Documentation of JavaScript methods and helpers in the legacy mongo shell.` there should be a link to the mongo legacy shell. This is one such example of an …
=> DOP-3211:  ref label

pyproject.toml, tools/bump_version.py
The "right" solution to this is to make the pyproject.toml version canonical, and use `importlib.metadata` (1), but let's do that once we bump our supported floor to python 3.8 as a separate decision.
(1): https://github.com/python-poetry/poetry/pull/2366#issuecomment-652418094
=> Make bump_version.py also bump the version in pyproject.toml

snooty/n.py, snooty/postprocess.py, snooty/test_language_server.py
Historically, mypy did not support recursive types. Consequently, our SerializableType definition had to fall back to Any.
Times change. SerializableType can now be defined in terms of itself. No more Any!
=> Make SerializableType recursive

poetry.lock, pyproject.toml
3.7 is hitting EOL in a few months, and we haven't actually been testing 3.7 in some time.
=> Bump minimum supported Python to 3.8

snooty/test_postprocess.py, snooty/test_types.py, snooty/types.py, test_data/test_postprocessor/snooty.toml, test_data/test_project/snooty.toml
In order to remove [this snooty config from cloud docs](https://github.com/10gen/cloud-docs/blob/master/snooty.toml#L1076), this is a pre-req to make versions an optional value.
Currently it serves no purpose. For the initial launch, all versions of the associated product that are active in repo_branches will be included. In the future, associated product version management should also happen within hapley / repo_branches to have a single source of truth, and not leave this "associated versioning" option to snooty configs.
Tested with doc repos with/without version specified, respectively produces:
vs
but these versions have no effect on the merged ToC outcome from the persistence module. image below shows resulting document with the versions configured. the persistence module adheres to …
=> DOP-3502: make associated_product.versions an optional field

snooty/diagnostics.py, snooty/parser.py, snooty/postprocess.py, snooty/rstspec.toml, snooty/test_postprocess.py
[DOP-3503](https://jira.mongodb.org/browse/DOP-3503)
Adds support for OpenAPI versions. Version data should be validated and passed as build metadata.
New openapi directive options called `versions` and `api-version` are implemented to allow the parser to source version data from APIx endpoints.
In-depth information on these changes and parameters [here](https://docs.google.com/document/d/1F2tmPnFM1Kj_gFZDAyWJUAO0M5L1Bd6xQ4pHTcmaI9M/edit#heading=h.bt6gg2flm4js).
Three thoughts and questions are provided below!
=> DOP-3503: Add OpenAPI Versioning support to parser

snooty/postprocess.py
Change to enable slugs which directly match a specified `associated-product.name` to be marked as external ref_project entries, to enable the current `atlas-cli` ToC entry within cloud docs to be replaced on release of embedded versions.
This change is required to allow matching for the existing Atlas-CLI entry (see https://mongodbcom-cdn.website.staging.corp.mongodb.com/docs-qa/atlas/cli/stable/) for an example of current behavior. Without this change, we'll have to try to synchronize the content change with the code deploy, which will add some risk to rollout.
=> Embedded Versions: allow slug to match as external toc node

snooty/parser.py
Tested to ensure that with SNOOTY_NO_AMBIGUOUS_LITERAL_DIAGNOSTICS=1 cloud-docs builds clean, but with SNOOTY_NO_AMBIGUOUS_LITERAL_DIAGNOSTICS not set it's warningspalooza
=> Add a temporary SNOOTY_NO_AMBIGUOUS_LITERAL_DIAGNOSTICS flag for cloud-docs

snooty/rstspec.toml
Include `api-version` option for `openapi` directive in rstspec.toml 
Seems like the test failures are normal for `latest`
=> Add openapi option: api-version

snooty/rstspec.toml
seems usage of steps was unclear. this attempts to clear up the difference between headings and paragraphs within steps
=> DOP-3530: update description for step directive in snooty.tmol

snooty/rstspec.toml, snooty/test_parser.py
DOP-3660
Adds openapi-changelog directive and api-version option.
=> DOP-3660: Add openapi-changelog directive

snooty/diagnostics.py, snooty/parser.py, snooty/postprocess.py, snooty/test_parser.py, snooty/test_postprocess.py
Emits error on duplicate `openapi_changelog` directives on a page.
Also, does legwork to account for `openapi_changelog` directives in `parser.py` and `postprocess.py`
=> DOP-3661: disallow duplicate changelog directives

snooty/diagnostics.py, snooty/parser.py, snooty/postprocess.py, snooty/rstspec-consolidated.toml, snooty/rstspec.toml, snooty/test_parser.py
Very simple PR. This validates that the only acceptable value for the `api-version` for the `openapi-changelog` directive is "2.0"
I've only added this to account in the future for when there will be more versions. An additional check.
=> DOP-3663: validate api-version for changelog

snooty/postprocess.py, snooty/test_postprocess.py
This makes `static_assets` not a lie when a page includes another.
=> DOP-3729: Update Page.static_assets set in IncludeHandler

snooty/rstspec.toml
question to reviewers: is there anywhere else in the snooty repo(s) that we should add the kotlin driver?
=> Add kotlin drivers to rst spec

snooty/rstspec.toml
Add two new roles for linking to manual versions:
- A general "upcoming" role, not tied to a specific docs version
- A role for v7.0
=> Add role to link to the upcoming manual docs

snooty/rstspec.toml
Updated the `oas-atlas-tag` and `oas-atlas-op` roles to point to the new versioned API. This should be merged and cherry-picked after we publish the versioned API docs tomorrow.
=> update atlas admin openapi links to use V2

snooty/diagnostics.py, snooty/page.py, snooty/page_database.py, snooty/parser.py, snooty/test_page_data.py, snooty/test_page_database.py
This approach uses `pickletools.optimize()`: while increasing persistence times dramatically (2.5s to 15.4s), it decreases load times from 4.0s to 1.8s using CPython 3.11.
Is this a worthwhile tradeoff? If cached builds are generated as a one-off batch-job, probably yes. If caching is generated on each build, absolutely not. Optimization can additionally be run offline as a separate job.
How we handle this and fine-tune what we persist and unpersist can be handled in the subsequent task.
Persist: 15.4s
Unpersist: 1.8s
Persist: 10.3s
Unpersist: 1.7s
=> DOP-3739: Implement simple PageData persistance and unpersistence

.github/workflows/test.yml, .gitignore, Makefile, tools/fetch-pyston.sh
```
CPython 3.11: 51.130s
Pyston:       41.841s
```
Pyston likely isn't a permanent solution, but provides a low-risk free performance bump in the medium-term.
=> DOP-3746: Use Pyston on linux amd64

snooty/main.py, snooty/page.py, snooty/page_database.py, snooty/parse_cache.py, snooty/parser.py, snooty/test_util.py, snooty/types.py, snooty/util.py
The ergonomics are open to change, but this PR does two things:
* It adds a new `create-cache` command that builds a parse cache in `<source-root>/.parsercache`
* If a `.parsercache` file is found in the source root, and if the *satisfaction conditions* defined below are met, then the cache is used to skip parsing files where possible. 
1. The cache file must be able to be unpickled into the expected classes without errors
2. The parser version string given in the cache file must match the version string in the running parser
3. The `rstspec.toml` and `pyproject.toml` files must match the cache file. The implementation of this check is a little overkill, and hashes the data rather than the plain text of these files, so comments and formatting can change without invalidating the cache. …
=> DOP-3740: Data cache layer

snooty/language_server.py, snooty/page.py, snooty/parse_cache.py, snooty/parser.py, snooty/test_parser.py, snooty/types.py
Allows a Page to depend on multiple other paths for the purposes of caching, so that if a `literalinclude` target changes, the page's parsed cache is invalidated.
=> Add page dependencies

snooty/postprocess.py, snooty/test_postprocess.py, snooty/test_types.py, snooty/types.py, test_data/test_project/snooty.toml
This adds the `canonical` tag to the `snooty.toml` file for pages that are completely EOL'd. 
In those edge cases, we are not able to programmatically determine the canonical tag or point to their current version as there is none. To solve this we give the writer the ability to provide us the desired location. 
The logic is then handled in Snooty, as it grabs the canonical URL and applies it to the canonical tag. 
More info can be found [here](https://github.com/mongodb/snooty/pull/857).
=> :sparkles: DOP-3865 adds canonical control from the .toml file

snooty/rstspec.toml
The @realm/react package and JS Web SDK both have new standalone reference docs. This PR adds roles for those references docs to make linking to them easier in the Realm docs.
Duplicate of #496, but based on `latest` branch.
=> Add new Realm sdk roles

snooty/parse_cache.py
With this change, with a no-op build of the server manual, we go from 285 misses to 0 misses, and the single-process `parse rst` time goes from 6.50s to 2.43s (as usual, minimum of three runs on the reference metric unit My Laptop).
=> DOP-3924: Cache assets including source constant substitutions

snooty/taxonomy.py, snooty/taxonomy.toml, snooty/test_parser.py, snooty/test_postprocess.py
[DOP-3932](https://jira.mongodb.org/browse/DOP-3932)
We should convert these in the parser, so that the facets.toml seed files that are generated as part of [DOP-3851](https://jira.mongodb.org/browse/DOP-3851) do not emit warnings for invalid fields. See issue description for schema definitions for reason for change
[Schema definition for targetPlatform](https://schema.org/targetPlatform)
[Schema definition for targetProduct](https://schema.org/targetProduct)
=> DOP-3932: convert target platforms to target products

snooty/taxonomy.py, snooty/taxonomy.toml, snooty/test_parser.py, snooty/test_postprocess.py, snooty/test_project.py, snooty/types.py, test_data/test_facets/source/driver-examples/facets.toml, test_data/test_facets/source/driver-examples/nest/facets.toml, test_data/test_facets/source/facets.toml
Based on [this comment](https://github.com/10gen/cloud-docs/pull/4768#issuecomment-1677379619) on cloud docs, we should not be pluralizing the taxonomy and facets.
This is necessary in order for the output of [facet generating scripts](https://github.com/10gen/snooty-scripts/tree/main/DOP-3851) to not throw an error, when run by the parser
This will require the parser to have been already released, before the script is run and merged into respective doc sites
=> DOP-3932 follow up: un pluralize taxonomy

snooty/taxonomy.toml
Minor comment in spreadsheet [here](https://docs.google.com/spreadsheets/d/1HvVo3REeyAUrOgicLsMMRVOQLmpNjFCbHxF4sNEOEK4/edit?disco=AAAA3LFXfss)
Requires for us to have `perl` as an option for programming language facets
=> DOP-3851: add perl programming language

snooty/main.py, snooty/types.py, test_data/test_project/source/facets.toml
**Goal:** serialize facets before outputting to document
When testing with this [PR for cloud-docs](https://github.com/10gen/cloud-docs/pull/4768), I encountered an encoding error on master branch (regarding document.facets):
```
(snooty-py3.11) ➜  snooty-parser git:(master) snooty build ../../doc-repos/cloud-docs --output=../../ast-zip/cloud-docs-DOP-3851-b-parsermaster.zip 
INFO:snooty.main:Snooty 0.14.4.dev starting
INFO:snooty.parser:cache: 0 hits and 1796 misses
Traceback (most recent call last):
File "/Users/seung.park/Library/Caches/pypoetry/virtualenvs/snooty-9xH0rLbM-py3.11/bin/snooty", line 6, in <module>
sys.exit(main())
^^^^^^
File "/Users/seung.park/Desktop/repositories/snooty-parser/snooty/main.py", line 299, in main
project.build()
File …
```
=> DOP-3921 follow up 

snooty/main.py
Without this, there is no way to create a cache file compatible with our infrastructure. Whoops.
=> Support passing options like --rstspec into the create-cache command

snooty/rstspec.toml
This PR: 
- updates the existing `kotlin-sdk` role to point to the base library
- adds a new `kotlin-sync-sdk` role, which points to the sync library
=> Split out Realm Kotlin SDK role to sync and base URLs

snooty/rstspec.toml
Jira: https://jira.mongodb.org/browse/DOCSP-32667
=> (DOCSP-32667) Makes MongoDB Atlas the top option on the language selector

snooty/gizaparser/extracts.py, snooty/gizaparser/nodes.py, snooty/gizaparser/parse.py, snooty/gizaparser/release.py, snooty/gizaparser/steps.py, snooty/gizaparser/test_extracts.py, snooty/gizaparser/test_nodes.py, snooty/gizaparser/test_parse.py, snooty/gizaparser/test_release.py, snooty/gizaparser/test_steps.py, snooty/language_server.py, snooty/main.py, snooty/n.py, snooty/page.py, snooty/parse_cache.py, snooty/parser.py, snooty/postprocess.py, snooty/rstparser.py, snooty/test_openapi.py, snooty/test_parser.py, snooty/test_postprocess.py, snooty/test_project.py, snooty/test_types.py, snooty/types.py, snooty/util.py, snooty/util_test.py
As demonstrated by the new code in `test_project.py::test_cache()`, caches are no longer path-dependent!
A notable change here is that since we now need a FileId for `snooty.toml`, that gets made with `FileId("../snooty.toml")` because FileIds are relative to the source directory.
=> DOP-3966: Make all internal path handling relative to the project source

snooty/parser.py, snooty/util_test.py
The whole diagnostics system is kind of a mess, but this should improve things and help ensure the invariant that, at least for a regular build, the two diagnostics reporting methods stay synchronized.
=> DOP-4008: Ensure that on_diagnostics() and set_diagnostics() stay in sync

snooty/rstspec.toml
Updating `rstspec.toml` on this branch to follow [this comment](https://github.com/mongodb/snooty-parser/pull/512#discussion_r1317632983) on original DOP-3855 snooty-parser [PR](https://github.com/mongodb/snooty-parser/pull/512) ([Jira ticket here](https://jira.mongodb.org/browse/DOP-3855)).
=> DOP-3855: updating rstspec.toml on latest branch

snooty/rstspec.toml, snooty/test_parser.py
[DOP-3992](https://jira.mongodb.org/browse/DOP-3992)
Instead of having the video directive be adjacent to the `landing:more-ways` directive, I decided to add an option to take the video URL so that the frontend can handle rendering the video component. This simplifies organizing and styling the content within the component. 
I'm not sure if this is an ideal approach, so I am definitely open to suggestions for an alternative for handling the video component.
=> [DOP-3992]: Add landing:more-ways directive

snooty/diagnostics.py, snooty/postprocess.py, snooty/rstspec.toml, snooty/test_postprocess.py
DOP-3993
* Adds an optional id to IA entries. This ID can be referenced by a `card-group` directive to link card data with an IA entry. This data will be usable in the side nav.
* The concept of linking data this way might be weird... This is for a (probably) one-off instance for the new homepage, but hopefully this is okay. I'm open to suggestions!
* Linked data will be present in the metadata to allow different pages with similar IA entries to render the linked data in multiple places.
* Relevant [frontend PR](https://github.com/mongodb/snooty/pull/890)
* Relevant [rST commit](https://github.com/mongodb/docs-landing/pull/132/commits/d157270c47a843add7f83e529357be7bcded8825)
=> DOP-3993: Allow card group to link data for IA entry

snooty/parse_cache.py, snooty/parser.py, snooty/rstspec.toml, snooty/specparser.py, snooty/util.py
We also gzip the cache files. Decompression of our largest file (Atlas) takes 100-200 milliseconds, but I judge it worthwhile for storage and bandwidth savings. In the future, switching to zstd would be worth it, but we don't need to think about that right now.
We also turn on pickle optimization by default to recoup some of that time cost.
=> DOP-4070: Automatically find a viable cache file from a given URL prefix

snooty/rstspec.toml
working on https://jira.mongodb.org/browse/DOCSP-33799 I noticed that we didn't have a shared role for adding links to mongodb university courses.
=> add link role for mongodb university courses

snooty/main.py
This saves a significant amount of time (5.5 seconds on my laptop) for some reason. There must be a number of atexit() handlers or something, but we've already flushed our output artifacts and child processes can exit asynchronously once their pipes are closed.
I don't love doing this, but it's required to meet our benchmark targets in lieu of some extended investigation that may or may not even be actionable
=> Use os._exit() to exit quickly once we've finished our work

snooty/diagnostics.py, snooty/postprocess.py, snooty/test_postprocess.py
The implementation within this PR focuses on detecting tabs that contain tabs that contain procedures. 
Some examples are
```
.. tabs::
.. tab::
.. tabs::
.. tab
.. include:: /includes/fact-a-procedure.rst
```
The modification happens in the `TabsSelectorHandler` class. The approach is as follows
Create two new stacks. When you enter a node first scan the pattern stack (holds the possible invalid patterns) and then append that node to the stack which acts as a container for all nodes, and when you exit a node pop the item off of that container stack, and when you exit a page clear the stacks altogether. 
This should only happen when entering a directive node.
1. `tabs > tab > include > tabs > tab > include > procedure`
2. `tabs > tab > tabs > tab > procedure`
3. `tabs > tab > section > …
=> :loud_sound: DOP-3898 adds warning message for invalid nesting of tabs

snooty/main.py, snooty/parser.py, snooty/test_project.py, snooty/test_util.py, snooty/types.py, snooty/util.py
Additionally make snooty.toml parsing errors generally fatal, rather than continuing with a blank project configuration.
=> DOP-4141: Catch TOML parsing errors in snooty.toml

snooty/rstspec.toml
The URI for the latest `@realm/react` API docs has changed since I added this role. It's a tiny update, but an important one. 😄
=> Update Realm SDK role URI

snooty/parser.py, snooty/test_parser.py, snooty/test_types.py
Previous PR overwrote user defined widths if they were supplied.
This PR addresses this so that images' and figures' option for width is preserved.
See updated test case to see the preservation in width/height ratio as well.
=> DOP-4207: preserve user width if specified

snooty/parser.py, snooty/test_parser.py, snooty/test_types.py, snooty/types.py
Goal: Remove warnings such as the following for images that do not need dimensions to preload in the browser.
```
WARNING(core/csfle/reference/encryption-components.txt:0ish): WARNING! Intrinsic size for image not calculated at path /Users/seung.park/Desktop/doc-repos/docs-mongodb-internal/source/images/client-side-field-level-encryption-diagram.svg. Image may not be lazy loaded.
```
Only the file formats that are defined in the constant are supported for image processing on the front end, and thus can be lazy loaded in the future.
=> DOP-4207: remove warning for svgs

snooty/postprocess.py, snooty/test_postprocess.py
**Goal:** Flag image directives for lazy loading, depending on their occurrence on the RST.
We can tweak the values for `min_section_depth` or `min_img_index`, but these were inspired from [this article for when to use lazy loading](https://web.dev/articles/lcp-lazy-loading?utm_source=lighthouse&utm_medium=devtools#testing_a_fix).
The front end portion is ready [here](https://github.com/mongodb/snooty/pull/981/files#diff-ffd2b22195ccbbae4128ae0f9aa63e3b223dec62b101275024fd4d21509f58e6R53). This will use Gatsby Image to lazy load components once they are in viewport
=> DOP-4225: flag images for lazy loading depending on 

snooty/postprocess.py, snooty/rstspec.toml, snooty/test_postprocess.py
[DOP-4279](https://jira.mongodb.org/browse/DOP-4279)
Instruqt labs are currently embedded into the content of a docs page but instead, we want them to appear after a click of a button next to the page's title heading. To accomplish this, the frontend must know if the page has a lab within the page AST.
([Current display of Instruqt Labs](https://github.com/mongodb/docs/blob/eea48f019634747775072cbf6bdf8c9ff13b4b79/source/tutorial/getting-started.txt#L29))
Page ASTs have a page-level option that determines if a lab should be shown.
The instruqt directive has support for a new title option
These changes were tested with tests added to test_processor.py. 
Only one Instruqt directive should be present per page; if there are two a diagnostic error will be produced.
=> DOP-4279: Parser identifies if an Instruqt lab is on the page

snooty/postprocess.py, snooty/rstspec.toml, snooty/test_postprocess.py
[DOP-4319](https://jira.mongodb.org/browse/DOP-4319)
`Drawer` option has been created for an Instruqt directive; the page-level `Instruqt` option will now be set based on the value of the Instruqt directive's drawer option, rather than entirely on whether an Instruqt directive exists on a page.
The `drawer` option is currently not required and the page level Instruqt option defaults to false if there a page's Instruqt lab doesn't have a drawer option set. This can be easily changed if desired
=> DOP-4319 added drawer option

snooty/icon_names.py
[DOP-4212](https://jira.mongodb.org/browse/DOP-4212)
To test the fix, I added an instance of the `mms-icon-modify` to a branch `docs meta` [here](https://github.com/mongodb/docs-meta/compare/master...DOP-4212#diff-5d81d5a2b93d3c24f68335ed516e6197236ef99e0c9f2740a33d4a8c24025fafR8463-R8466). I then ran the parser on it once without the parser fix, and once with; without the fix, the error appears, with the fix, there's no error.
=> DOP-4212: mms-icon-modify renders but causes a build error

snooty/main.py
Example from building Sarah's branch:
```812 diagnostics; 4164 pages; 193 assets```
=> DOP-4336: Log a final summary message

snooty/test_parser.py, snooty/tinydocutils/states.py, test_data/test_parser/sample@2x.png
Parsing emails into mailto: reference nodes is a current docutils behavior that we have never tested or encouraged, and probably is not something we want to begin with.
The easiest fix for this ticket is to remove email parsing. If there's need, it would probably be better to introduce a role for this. This (mis)feature is not used in the server manual corpus, but is used once in the Atlas docs.
The alternative approach would be to not inline parse all directive arguments. This perhaps should be done also at some point, but would change the AST so we should be cautious in doing so.
=> DOP-3285: Don't parse emails

snooty/rstparser.py, snooty/test_parser.py, snooty/tinydocutils/states.py
Our approach here is to add a stack of "minimum heading levels" to our parsing memo. When we enter and exit a directive, we push and pop the current heading level, respectively.
This allows us to warn when we encounter a section with an unacceptably low section level.
=> DOP-3969: Raise a diagnostic for section structures that cannot fit into a tree

snooty/test_parser.py, snooty/types.py
DOP-4408
- Minimal change to allow for SVG's to have calculated width/height attached to its AST node
- Included test to reflect size attributes being added
=> DOP-4408: include svg as part of deriving width/height

snooty/diagnostics.py
DOP-4320
Converting the nested tab output from a warning to an info.
=> :loud_sound: DOP-4320 switches from warning to info to help filter output

snooty/main.py, snooty/postprocess.py, snooty/test_main.py, snooty/util.py
DOP-4447
- This change adds a check for file extension, in which case the parser will not save a bson to the zip file, therefore not handed to search manifests or snooty
=> DOP-4447: skip files that do not end with .txt 

snooty/gizaparser/extracts.py, snooty/gizaparser/test_extracts.py, test_data/test_gizaparser/source/includes/extracts-test.yaml
DOP-4495
Giza extracts supported the pre/post keys we see in other types of YAML files. We neglected to support this when we implemented our Giza compatibility layer.
Add support for these keys.
=> DOP-4495: Support pre and post in extracts

.github/workflows/release.yml
DOP-4479
Test workflow succeeded in https://github.com/mongodb/snooty-parser/actions/runs/8573383377. Confirmed that a release was made with both assets attached.
=> DOP-4479: Update github actions

snooty/rstspec.toml
DOP-4511
The role approach would make sense, except the badge LG component renders with a `<div>` which doesn't work for an inline paragraph-y element. Accordingly, changing this to a directive to reduce invalid HTML sadness.
=> DOP-4511: make comm driver a directive

.github/workflows/test.yml
Python 3.8 is hitting EOL this October, but for now we want to retain Pyston, which is stuck at version 3.8.
=> Exclude Python 3.8 on macOS from the action matrix

snooty/postprocess.py, snooty/test_postprocess.py
DOP-4592
`slugToTitle` uses the full title fields of pages. Breadcrumbs and back/forward buttons in Snooty should use the condensed TOC labels. This creates a field `slugToBreadcrumbLabel` on the metadata as well and parses the TOC labels to have on hand if possible, and if not, uses the `title` field. 
=> DOP-4592: Parse breadcrumb toc titles

snooty/parser.py, snooty/test_parser.py
DOP-4430
This change ensures that the amount of `:header-rows:` specified for a `list-table` directive is less than the amount of total rows. If not, it throws the error: `ERROR(<file:line>): List-table cannot have only header rows` and does not add the table to the resulting AST.
[This is the resulting staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/compass/maya/main/editions/index.html) for [this example PR](https://github.com/mongodb/docs-compass/pull/626/files). The table does not get created ([same page in prod](https://www.mongodb.com/docs/compass/current/editions/)).
- - [x] This PR does not introduce changes that should be …
=> DOP-4430: Add diagnostic warning when a table has only 1 header row

snooty/language_server.py, snooty/parser.py, snooty/test_language_server.py
DOP-4441
Adds a method to get original YAML file paths for rST files that have been converted from YAML files to support the [clickInclude](https://github.com/mongodb/snooty-vscode/blob/main/src/extension.ts#L102) function in the VSCode extension.
=> DOP-4441: Improve snooty.clickInclude command in VSCode extension

snooty/diagnostics.py, snooty/eventparser.py, snooty/postprocess.py, snooty/test_postprocess.py
DOP-4723
It struck me by chance that we don't have cycle detection in our include logic. It hasn't come up, but let's make sure we handle that situation gracefully before it does.
=> DOP-4723: Detect include loops

snooty/rstparser.py, snooty/test_parser.py
DOP-4745
This is obnoxious.
The trick here is that we're running `nested_parse()` on the *argument*, not the content, but have been passing `content_offset` to `nested_parse()`. As a result, `content_offset` is out of sync with the actual string list being passed in, and for unknowable reasons this causes an IndexError in the specific case we have here.
=> DOP-4745: Fix IndexError in tinydocutils

snooty/diagnostics.py, snooty/main.py, snooty/page_database.py, snooty/test_main.py, snooty/util.py
Two categories of change are afoot here to ensure repeatable builds:
* Sorting data
* Removing timestamps
=> Make repeated bundle builds bit-identical

snooty/diagnostics.py, snooty/parser.py, snooty/postprocess.py, snooty/rstspec.toml, snooty/test_parser.py, snooty/test_postprocess.py
DOP-4690
**Changes from this PR**
- Adds `.. collapsible:: ` directive into our rstspec, and handles new ReSTructured text into expected AST
has `heading:string (required)` and `sub_heading.string` options, along with a required `content_type:block` 
- Adds Error level Diagnostics for missing content block within collapsible directive
- Adds Error level Diagnostics for nested collapsibles
- Inserts the `heading` option from new directive into `page.ast.options.headings[]` during postprocess so that this can be included in the right column for `On this page`. Discussed offline with @i80and that the alternative to this would be to enforce a heading and subheading structure within the `content_type`, but no strong opinions here
- - [ ] This PR introduces changes that should be reflected in …
=> DOP-4690: prepare parser for new collapsible directive

snooty/diagnostics.py, snooty/parser.py, snooty/postprocess.py, snooty/rstspec.toml, snooty/specparser.py, snooty/test_parser.py, snooty/test_postprocess.py
DOP-4692
[Related frontend PR](https://github.com/mongodb/snooty/pull/1192)
[Designs](https://www.figma.com/design/7cR6eWtFvKTnJIPL8ZsTaB/Content-Template-Projects?node-id=3147-3388&t=PnibGktO5uVkJEtU-0)
[rST example](https://github.com/rayangler/cloud-docs/blob/test-wayfinding/source/testing-wayfinding.txt)
* I opted to create a separate directive for the description inside of the `wayfinding` directive instead of using some `description` option because (1) it allows the component to be more flexible for different use cases and copy if needed, and (2) it allows the use of an `include` directive to make it easier to share copy for related instances of the directive.
- - [ ] This PR introduces changes that should be reflected in the README.md and/or HACKING.md, and I have made those …
=> DOP-4692: Implement wayfinding directives

snooty/diagnostics.py, snooty/parser.py, snooty/postprocess.py, snooty/rstspec.toml, snooty/specparser.py, snooty/test_parser.py, snooty/test_postprocess.py
DOP-4685
[Example rST](https://github.com/rayangler/cloud-docs/blob/ace163b51c2f157f38a6d044d2a5faea63b287d3/source/testing-method-selector.txt)
[Designs](https://www.figma.com/design/7cR6eWtFvKTnJIPL8ZsTaB/Content-Template-Projects?node-id=3473-22389&t=RNnOtvg64NtvtUHi-0)
[Related frontend PR](https://github.com/mongodb/snooty/pull/1208)
* There were a lot of similarities to the `wayfinding` directive, so I tried my best to make the logic more reusable. Let me know if there are any issues with anything.
* There's a weird bug where headings inside of this directive aren't captured in the `ContentsHandler` for some reason. I'm hoping to look into this as a separate ticket since it doesn't affect the component itself. I don't think this should be a blocker for this PR considering the "On …
=> DOP-4685: Implement method-selector

snooty/rstspec.toml, snooty/test_parser.py
DOP-4972
[Staging link example](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/dark-mode-enable/DOP-4683/cloud-docs/maya/DOP-4972/testing-wayfinding/index.html)
Adding Ruby driver to wayfinding options.
=> DOP-4972: Add ruby driver to wayfinding component

snooty/postprocess.py, snooty/rstspec.toml, snooty/test_postprocess.py, snooty/types.py
DOP-4689
[Design](https://www.figma.com/design/7cR6eWtFvKTnJIPL8ZsTaB/Content-Template-Projects?node-id=3479-1567&node-type=FRAME&t=fi9vNQKAIxOCjzaG-0)
[rST example](https://github.com/rayangler/cloud-docs/commit/aa19b8cca34a4613fe75a0e3d3c31ab8c76d7345)
[Frontend PR](https://github.com/mongodb/snooty/pull/1225)
[SPIKE doc](https://docs.google.com/document/d/1cR_YWkeEUnVTo5tNFdlt9L_oy1CwpyU9kG1jfBnj1QA/)
* The original ticket was supposed to be for the frontend, but it turns out that the parser portion was never formally implemented. Referenced the POC code from the SPIKE doc to help implement.
* The approach is split into two parts:
* snooty.toml is updated to include parent page paths of a TOC tree as a multi-page tutorial. Immediate children of that page's TOC will be considered …
=> DOP-4689: Implement multi-page tutorials

snooty/parser.py, snooty/postprocess.py, snooty/test_parser.py, snooty/test_postprocess.py
DOP-4983
- Ticket fixes sectioning depth by adding a section into collapsible content (if one does not already exist in the direct children)
- Ticket addresses heading options for the AST, where wrong headings would be contained within the page options
- Unit tests have been added to identify above situations
=> DOP-4983: improve heading content and sectioning

snooty/diagnostics.py, snooty/parser.py, snooty/rstspec.toml, snooty/specparser.py, snooty/test_parser.py
DOP-4917
[Related frontend PR](https://github.com/mongodb/snooty/pull/1236)
[Example rST](https://github.com/rayangler/cloud-docs/commit/93ab9b1cc34c1a461e8266da44f07687acc49c49)
* I know the original ticket didn't ask for a `description` option, but I saw this [Google Rich Result test](https://search.google.com/test/rich-results/result?id=NWG835UY5-cwJQ_1l8KR-A) that showed a single warning and figured it's worth including for completion.
* All options are not required for the `video` directive to be used on a page, in order to allow for backwards compatibility. However, a warning will be added whenever one of the options is used without the use of all other options for structured data. The frontend will handle whether to show the structured data or not based on the options available.
* …
=> DOP-4917: Add video options for video metadata

snooty/postprocess.py, snooty/test_postprocess.py
DOP-4967
Adds `selector_id` to heading if they belong to a certain method option. Can be extended to tab options in the future. 
See [PR in Snooty](https://github.com/mongodb/snooty/pull/1237)
=> DOP-4967: Contextualize headings in method selector for "On This Page" list

snooty/n.py, snooty/postprocess.py, snooty/test_postprocess.py
DOP-4959
In prod currently, breadcrumbs and prevnext button text only have the title's first node's text. This works for most titles. This PR includes inline literals.
[Current prod](https://www.mongodb.com/docs/mongodb-shell/reference/configure-shell-settings-global/)
[Staging](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-4942-dark-icons-master/mongodb-shell/matt.meigs/main/reference/configure-shell-settings-global/index.html)
=> DOP-4959: parse literals in titles

snooty/postprocess.py, snooty/taxonomy.py, snooty/test_postprocess.py, snooty/types.py
DOP-4915
This is a prereq to the structured data being displayed on the front end. (see this tech spec for TechArticle section that specifies that we need to construct Structured Data based on the `target_platform` property of facets.
These changes extract the `display_name` from the [taxonomy file](https://github.com/mongodb/snooty-parser/blob/main/snooty/taxonomy.toml) and appends them to the produced `page.facets`.
=> DOP-4915: add display_name property to facets

snooty/postprocess.py, snooty/test_postprocess.py
DOP-3424
Creates a `selector_ids` object that reflects the AST in terms of the order of tabs/method selectors. This object looks something like this:
```
method-option: abc
children: {
tab: def
children: {
tab: efg
}
}
```
This is used by snooty ([see PR](https://github.com/mongodb/snooty/pull/1262)) to determine correct headings to show.
=> DOP-3424: "On this page" subnav incorrectly displays headings for all language tabs

snooty/diagnostics.py, snooty/postprocess.py, snooty/rstspec.toml, snooty/test_postprocess.py
DOP-4945
New optional option `:default-tabid:` for `tabs-selector` and `tabs-pillstrip` directives for use with drivers tabs.
Staging links available on sister PR in snooty [here](https://github.com/mongodb/snooty/pull/1301).
=> DOP-4945: Default tab available for drivers tabs

snooty/rstspec.toml, snooty/test_parser.py
DOP-5130
Collapsible expanded option is now a boolean rather than a flag.
Snooty PR [here](https://github.com/mongodb/snooty/pull/1306).
=> DOP-5130: Collapsible `:expanded:` option as boolean

snooty/postprocess.py, snooty/test_postprocess.py
DOP-5135
* Removes nested directive error for `method-selector`, as requested by the docs team. Approach was to detach the postprocess handler for `method-selector` from its superclass that handled checking for both nested directives and duplicate directives.
* Removes tests related to instances of `method-selector` nested in other directives.
=> DOP-5135: Remove nested directive error for method-selector

CHANGELOG.md, snooty/postprocess.py, snooty/test_postprocess.py
DOP-5240
* Default tabid was not being reset whenever a new page was entered. The persisted data from a previous page would then affect the validations and default tabid for a subsequent page, even if it did not have a default tabid set.
=> DOP-5240: Ensure default tabids don't persist across pages

snooty/rstspec.toml
[DOCSP-45974](https://jira.mongodb.org/browse/DOCSP-45974)
As part of the docs SEO technical fixes, we'd like to update the Atlas CLI link from `/stable` to `/current`.
=> DOCSP-45974 updated atlas cli link

snooty/main.py, snooty/page.py, snooty/parser.py, snooty/test_parser.py, snooty/util.py
DOP-5250
* I originally thought that [this line](https://github.com/mongodb/snooty-parser/blob/2c537a2cdee274f957b11c6ed5e0cdf35b10750e/snooty/parser.py#L1881) was enough to treat pages created from `.ast` files to be the same as `.txt` files, but turns out that was wrong. This PR ensures that `.ast` files have a `.txt` fileid to match the parser's, frontend's, persistence module's, etc.'s, assumptions of a page AST having a `.txt` fileid. 
* The potential con of this approach is that diagnostics for `.ast` files will now include a fileid with a `txt` extension, which might be confusing for anyone who sees `ast`-related issues and are not familiar with the conversion.
* This PR also fixes uncaught bugs that were happening because `.ast` files weren't properly going through the …
=> DOP-5250: Consider .ast files as .txt page

snooty/postprocess.py
DOP-5303
* There was an additional change that needed to be done to allow facets to be propagated properly to ast files.
**To test:**
1. Go to this [staging link](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/master/java/raymund.rodriguez/DOP-5303/api-documentation/java-sync/com/mongodb/client/package-summary/index.html)
2. Open up dev tools and go to the network tab.
3. Look for `page-data.json` for the current staged page. Navigate to `result.data.page.facets` and the repo-wide facets should now be there, along with the new "reference" genre facet.
=> DOP-5303: Handle ast file facets in postprocessor

snooty/postprocess.py, snooty/util.py
DOP-5329
Adds ability to deserialize toctree nodes.
Uses new osiris property `osiris_parent` to delineate which toctree nodes should not be drawers.
Necessary for [this Osiris PR](https://github.com/10gen/osiris/pull/33).
=> DOP-5329: Osiris TOC

snooty/rstspec.toml
https://jira.mongodb.org/browse/DOCSP-48367
* Adds a set of "relational-db" tabs for use in Relational Migrator docs
=> DOCSP-48367 Added relational-dbs for the tab directive

snooty/parser.py, snooty/test_parser.py
DOP-5477
This is a follow up to [the previous PR.](https://github.com/mongodb/snooty-parser/pull/652)
This change allows users to define composable options in any order (previously was getting the order defined from the rstspec)
Also dedupes choices in the selections.
Updated the unit tests to reflect these cases
=> DOP-5477 Follow up - strict order on composable options, dedupe selections

snooty/gizaparser/release.py, snooty/gizaparser/steps.py, snooty/n.py, snooty/parser.py, snooty/rstparser.py, snooty/rstspec.toml, snooty/test_parser.py
Following the changes made in PR #389 , this PR adds a new "category" string option to:
- `code-block`
- The `input` block of `io-code-block`
- `literalinclude`
It intentionally omits a category on the `output` block because that will always be of "Return object" category - no need for writers to specify that.
Writers can use this to supply the category of a code example for internal programmatic tracking. This currently has no frontend use.
=> Add category option to code-related directives

snooty/postprocess.py, snooty/test_postprocess.py
DOP-5589
This ticket stores heading info under Composable Tutorials into the page option, so that front end can consume this dynamically. 
See [front end changes here](https://github.com/mongodb/snooty/pull/1412)
See [staged front end here](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-5507/landing/seung.park/DOP-5589/composable-tutorials/index.html?deployment-type=self&interface=atlas-admin-api&operator=autocomplete)
=> DOP-5589: Composable tutorials dynamic headings

snooty/util.py
N/A
* See https://github.com/mongodb/netlify-extensions/pull/124 for more information. Tl;dr is that the old proxy serverless function was getting difficult to maintain and a Netlify backend issue caused the original serverless function to stop working, so we had to move it to make it easier to redeploy.
=> Fix sharedinclude proxy

snooty/rstspec.toml
DOP-5873
* Adds new `oas-bump-atlas` roles that will eventually replace existing `oas-atlas` roles. The new roles should use the URL structure of the new Bump pages. This was desired to be a separate role so that writers can update their usage in the docs when they're ready without introducing breaking changes.
* In case a staging links are needed for testing, I modified some content locally to work (there won't be examples available in prod/preprod):
* [oas-bump-atlas-tag](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-5873-oas-roles/cloud-docs/raymund.rodriguez/main/access-tracking/index.html) - Go to the "Atlas Administration API" tab at the bottom and see the "Access Tracking" link.
* [oas-bump-atlas-op](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-5873-oas- …
=> DOP-5873: Add new oas-bump-atlas roles

snooty/postprocess.py, snooty/test_postprocess.py, snooty/util.py
DOP-5816
Currently, the parser assumes that any `txt` file should be parsed as reStructuredText and be counted as a page. This PR makes it so that the `code-examples` directory is treated as a special directory name reserved for code examples, and not pages.
I created a staging link that did not result in any orphan page errors: 
* [Page that uses literalincludes and includes](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-5816-code-examples/docs/raymund.rodriguez/main/test-page/index.html)
* [Page that is named "code-examples"](https://docs-mongodb-org-stg.s3.us-east-2.amazonaws.com/DOP-5816-code-examples/docs/raymund.rodriguez/main/style/code-examples/index.html)
* [rST source](https://github.com/10gen/docs-mongodb-internal/compare/main...rayangler:docs-mongodb-internal:DOP- …
=> DOP-5816: Avoid parsing txt files in reserved directories

CHANGELOG.md, pyproject.toml, snooty/__init__.py, snooty/rstspec.toml, snooty/test_parser.py
DOP-6049
Adds two new directives (multi-column, and column).
=> DOP-6049 adds new directives called multi-column and column
